package com.github.klboke.kkrepo.compat;

import com.github.klboke.kkrepo.protocol.alpine.AlpineChecksums;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.time.Instant;
import java.util.Base64;
import java.util.Date;
import java.util.HexFormat;
import java.util.List;
import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveOutputStream;
import org.apache.commons.compress.compressors.gzip.GzipCompressorOutputStream;
import org.apache.commons.compress.compressors.gzip.GzipParameters;

/** Small installable APK v2 and RSA signing fixtures for live compatibility checks. */
final class AlpineCompatibilityFixtures {
  private AlpineCompatibilityFixtures() {
  }

  static ApkPackage apk(String name, String version, String marker) throws Exception {
    byte[] markerBytes = (marker + "\n").getBytes(StandardCharsets.UTF_8);
    byte[] data = tarGzip(List.of(
        Entry.directory("usr/"),
        Entry.directory("usr/share/"),
        Entry.directory("usr/share/kkrepo-alpine-compat/"),
        Entry.file("usr/share/kkrepo-alpine-compat/" + name + ".txt", markerBytes, true)), true);
    String dataSha256 = digest("SHA-256", data);
    String pkgInfo = "# Generated by kkRepo compatibility tests\n"
        + "pkgname = " + name + "\n"
        + "pkgver = " + version + "\n"
        + "pkgdesc = kkRepo Alpine compatibility fixture\n"
        + "url = https://kkrepo.invalid/alpine/" + name + "\n"
        + "builddate = 1786665600\n"
        + "packager = kkRepo Compatibility <compat@kkrepo.invalid>\n"
        + "size = " + markerBytes.length + "\n"
        + "arch = noarch\n"
        + "origin = " + name + "\n"
        + "maintainer = kkRepo Compatibility <compat@kkrepo.invalid>\n"
        + "license = MIT\n"
        + "datahash = " + dataSha256 + "\n";
    byte[] control = tarGzip(List.of(Entry.file(
        ".PKGINFO", pkgInfo.getBytes(StandardCharsets.UTF_8), false)), false);
    byte[] bytes = new byte[control.length + data.length];
    System.arraycopy(control, 0, bytes, 0, control.length);
    System.arraycopy(data, 0, bytes, control.length, data.length);
    return new ApkPackage(
        name + "-" + version + ".apk",
        name,
        version,
        bytes,
        AlpineChecksums.v2Identity(control),
        dataSha256,
        digest("SHA-256", bytes));
  }

  static SigningKey signingKey() throws Exception {
    KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
    generator.initialize(2048);
    KeyPair pair = generator.generateKeyPair();
    return new SigningKey(
        pem("PRIVATE KEY", pair.getPrivate().getEncoded()), pair.getPublic());
  }

  private static byte[] tarGzip(List<Entry> entries, boolean terminal) throws Exception {
    ByteArrayOutputStream tarBytes = new ByteArrayOutputStream();
    try (TarArchiveOutputStream tar = new TarArchiveOutputStream(tarBytes)) {
      tar.setLongFileMode(TarArchiveOutputStream.LONGFILE_ERROR);
      tar.setBigNumberMode(TarArchiveOutputStream.BIGNUMBER_ERROR);
      for (Entry value : entries) {
        TarArchiveEntry entry = new TarArchiveEntry(value.name());
        entry.setMode(value.directory() ? 0755 : 0644);
        entry.setUserId(0);
        entry.setGroupId(0);
        entry.setUserName("root");
        entry.setGroupName("root");
        entry.setModTime(Date.from(Instant.ofEpochSecond(1_786_665_600L)));
        if (value.directory()) {
          entry.setSize(0);
        } else {
          entry.setSize(value.bytes().length);
          if (value.apkChecksum()) {
            entry.addPaxHeader("APK-TOOLS.checksum.SHA1", digest("SHA-1", value.bytes()));
          }
        }
        tar.putArchiveEntry(entry);
        if (!value.directory()) tar.write(value.bytes());
        tar.closeArchiveEntry();
      }
      tar.finish();
    }
    byte[] archive = tarBytes.toByteArray();
    int meaningful = archive.length;
    while (meaningful >= 512 && zeroBlock(archive, meaningful - 512)) meaningful -= 512;
    int length = meaningful + (terminal ? 1024 : 0);
    byte[] fragment = java.util.Arrays.copyOf(archive, length);
    GzipParameters parameters = new GzipParameters();
    parameters.setModificationInstant(Instant.EPOCH);
    parameters.setFilename(null);
    ByteArrayOutputStream compressed = new ByteArrayOutputStream();
    try (GzipCompressorOutputStream gzip =
        new GzipCompressorOutputStream(compressed, parameters)) {
      gzip.write(fragment);
    }
    return compressed.toByteArray();
  }

  private static boolean zeroBlock(byte[] bytes, int offset) {
    for (int index = offset; index < offset + 512; index++) {
      if (bytes[index] != 0) return false;
    }
    return true;
  }

  private static String digest(String algorithm, byte[] bytes) throws Exception {
    return HexFormat.of().formatHex(MessageDigest.getInstance(algorithm).digest(bytes));
  }

  private static String pem(String type, byte[] bytes) {
    String value = Base64.getMimeEncoder(64, new byte[]{'\n'}).encodeToString(bytes);
    return "-----BEGIN " + type + "-----\n" + value + "\n-----END " + type + "-----\n";
  }

  private record Entry(String name, byte[] bytes, boolean directory, boolean apkChecksum) {
    private static Entry directory(String name) {
      return new Entry(name, new byte[0], true, false);
    }

    private static Entry file(String name, byte[] bytes, boolean apkChecksum) {
      return new Entry(name, bytes.clone(), false, apkChecksum);
    }
  }

  record ApkPackage(
      String filename,
      String name,
      String version,
      byte[] bytes,
      String identity,
      String dataSha256,
      String sha256) {
    @Override
    public byte[] bytes() {
      return bytes.clone();
    }
  }

  record SigningKey(String privatePem, java.security.PublicKey publicKey) {
  }
}
