package com.github.klboke.kkrepo.server.alpine;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.List;
import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveOutputStream;
import org.apache.commons.compress.compressors.gzip.GzipCompressorOutputStream;

/** Small, structurally valid APK v2 fixtures for server tests. */
final class AlpineTestPackage {
  private AlpineTestPackage() {
  }

  static Fixture apk(String name, String version, String architecture) throws IOException {
    return apk(name, version, architecture,
        List.of(
            new Item("usr/", new byte[0], null),
            new Item("usr/bin/", new byte[0], null),
            new Item("usr/bin/" + name, "fixture".getBytes(StandardCharsets.UTF_8), null)));
  }

  static Fixture apk(
      String name, String version, String architecture, List<Item> dataEntries) throws IOException {
    byte[] data = gzipTar(dataEntries, true);
    String pkgInfo = """
        # Generated by kkRepo tests
        pkgname = %s
        pkgver = %s
        pkgdesc = Alpine fixture package
        url = https://example.invalid/%s
        builddate = 1786665600
        packager = kkRepo Test <test@example.invalid>
        size = 7
        arch = %s
        origin = %s
        maintainer = kkRepo Test <test@example.invalid>
        license = MIT
        depend = musl
        provides = cmd:%s=1
        datahash = %s
        """.formatted(
            name, version, name, architecture, name, name, sha256(data));
    byte[] control = gzipTar(List.of(
        new Item(".PKGINFO", pkgInfo.getBytes(StandardCharsets.UTF_8), null)), false);
    return new Fixture(concatenate(control, data), control, data, pkgInfo);
  }

  static byte[] gzipTar(List<Item> entries) throws IOException {
    return gzipTar(entries, true);
  }

  private static byte[] gzipTar(List<Item> entries, boolean terminal) throws IOException {
    ByteArrayOutputStream tarBytes = new ByteArrayOutputStream();
    try (TarArchiveOutputStream tar = new TarArchiveOutputStream(tarBytes)) {
      tar.setLongFileMode(TarArchiveOutputStream.LONGFILE_ERROR);
      for (Item item : entries) {
        TarArchiveEntry entry;
        if (item.name().endsWith("/")) {
          entry = new TarArchiveEntry(
              item.name(), org.apache.commons.compress.archivers.tar.TarConstants.LF_DIR);
          entry.setSize(0);
        } else if (item.linkTarget() != null) {
          entry = new TarArchiveEntry(
              item.name(), org.apache.commons.compress.archivers.tar.TarConstants.LF_SYMLINK);
          entry.setLinkName(item.linkTarget());
          entry.setSize(0);
        } else {
          entry = new TarArchiveEntry(item.name());
          entry.setSize(item.bytes().length);
          if (terminal) {
            entry.addPaxHeader("APK-TOOLS.checksum.SHA1", sha1(item.bytes()));
          }
        }
        tar.putArchiveEntry(entry);
        if (item.linkTarget() == null) tar.write(item.bytes());
        tar.closeArchiveEntry();
      }
      tar.finish();
    }
    byte[] archive = tarBytes.toByteArray();
    int fragmentSize = archive.length;
    while (fragmentSize >= 512 && zeroBlock(archive, fragmentSize - 512)) fragmentSize -= 512;
    if (terminal) fragmentSize += 1024;
    if (archive.length < fragmentSize) throw new IOException("Incomplete test tar archive");
    ByteArrayOutputStream bytes = new ByteArrayOutputStream();
    try (GzipCompressorOutputStream gzip = new GzipCompressorOutputStream(bytes)) {
      gzip.write(archive, 0, fragmentSize);
    }
    return bytes.toByteArray();
  }

  static byte[] concatenate(byte[]... members) throws IOException {
    ByteArrayOutputStream result = new ByteArrayOutputStream();
    for (byte[] member : members) result.write(member);
    return result.toByteArray();
  }

  static String sha256(byte[] bytes) {
    try {
      return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
    } catch (NoSuchAlgorithmException impossible) {
      throw new IllegalStateException(impossible);
    }
  }

  private static String sha1(byte[] bytes) {
    try {
      return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-1").digest(bytes));
    } catch (NoSuchAlgorithmException impossible) {
      throw new IllegalStateException(impossible);
    }
  }

  private static boolean zeroBlock(byte[] bytes, int offset) {
    for (int index = offset; index < offset + 512; index++) {
      if (bytes[index] != 0) return false;
    }
    return true;
  }

  record Fixture(byte[] bytes, byte[] controlMember, byte[] dataMember, String pkgInfo) {
    Fixture {
      bytes = bytes.clone();
      controlMember = controlMember.clone();
      dataMember = dataMember.clone();
    }

    @Override
    public byte[] bytes() {
      return bytes.clone();
    }

    @Override
    public byte[] controlMember() {
      return controlMember.clone();
    }

    @Override
    public byte[] dataMember() {
      return dataMember.clone();
    }
  }

  record Item(String name, byte[] bytes, String linkTarget) {
    Item(String name, byte[] bytes) {
      this(name, bytes, null);
    }

    Item {
      bytes = bytes == null ? new byte[0] : bytes.clone();
    }

    @Override
    public byte[] bytes() {
      return bytes.clone();
    }
  }
}
