package com.github.klboke.kkrepo.server.securityscan;

import com.github.klboke.kkrepo.persistence.jdbc.api.SecurityScanDao.ScanTask;

/**
 * Identifies one claimed lease, rather than the durable task across all retries.
 *
 * <p>The task row is reused when an expired lease is reclaimed or an administrator retries it,
 * and administrative retry resets the attempt counter. The random lease token is regenerated by
 * every claim, so cancellation from an old owner cannot interrupt work started by the replacement
 * owner.
 */
final class SecurityScanExecutionId {
  private SecurityScanExecutionId() {}

  static String from(ScanTask task) {
    if (task == null) throw new IllegalArgumentException("Scan task is required");
    if (task.leaseToken() == null || task.leaseToken().isBlank()) {
      throw new IllegalArgumentException("Claimed scan task lease is required");
    }
    return task.id() + ":" + task.leaseToken();
  }
}
