CREATE TABLE pub_upload_session (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  repository_id BIGINT UNSIGNED NOT NULL,
  session_id VARCHAR(128) NOT NULL,
  field_token VARCHAR(128) NOT NULL,
  principal_user_id VARCHAR(255) NULL,
  principal_api_key_id BIGINT UNSIGNED NULL,
  status VARCHAR(32) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  blob_store_id BIGINT UNSIGNED NULL,
  blob_ref VARCHAR(1024) NULL,
  object_key VARCHAR(2048) NULL,
  md5 CHAR(32) NULL,
  sha1 CHAR(40) NULL,
  sha256 CHAR(64) NULL,
  sha512 CHAR(128) NULL,
  size BIGINT UNSIGNED NULL,
  package_name VARCHAR(128) NULL,
  version VARCHAR(255) NULL,
  pubspec_json JSON NULL,
  error_message VARCHAR(2048) NULL,
  finalized_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_pub_upload_session (repository_id, session_id),
  KEY idx_pub_upload_session_status_expires (status, expires_at),
  KEY idx_pub_upload_session_repository_package (repository_id, package_name, version),
  CONSTRAINT fk_pub_upload_session_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE,
  CONSTRAINT fk_pub_upload_session_blob_store FOREIGN KEY (blob_store_id) REFERENCES blob_store (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
