#!/usr/bin/env python3
"""Create a small deterministic, installable APK v2 package fixture."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import json
import pathlib
import re
import subprocess
import tarfile


PACKAGE_RE = re.compile(r"[a-z0-9][a-z0-9+_.-]{0,127}\Z")
# This fixture only needs a bounded lexical guard; apk-tools remains the semantic oracle for
# ordering. A flat character class keeps validation linear even for adversarial CLI input.
VERSION_RE = re.compile(r"[0-9][0-9A-Za-z._+~-]{0,127}\Z")
ARCH_RE = re.compile(r"[a-z0-9][a-z0-9_-]{0,63}\Z")
GZIP_MAGIC = b"\x1f\x8b"


def tar_gzip(
    entries: list[tuple[str, bytes, int]],
    timestamp: int,
    *,
    terminal: bool,
    compresslevel: int = 9,
) -> bytes:
    # APK v2 is one tar archive split across concatenated gzip streams. Intermediate
    # signature/control streams must not contain tar end markers; only the data stream does.
    tar_buffer = io.BytesIO()
    with tarfile.open(fileobj=tar_buffer, mode="w", format=tarfile.PAX_FORMAT) as archive:
        for name, data, mode in entries:
            entry = tarfile.TarInfo(name)
            directory = name.endswith("/")
            entry.type = tarfile.DIRTYPE if directory else tarfile.REGTYPE
            entry.size = 0 if directory else len(data)
            entry.mode = mode
            entry.uid = 0
            entry.gid = 0
            entry.uname = "root"
            entry.gname = "root"
            entry.mtime = timestamp
            if terminal and not directory:
                entry.pax_headers["APK-TOOLS.checksum.SHA1"] = hashlib.sha1(data).hexdigest()
            archive.addfile(entry, None if directory else io.BytesIO(data))
    raw_tar = tar_buffer.getvalue()
    meaningful_size = 0
    with tarfile.open(fileobj=io.BytesIO(raw_tar), mode="r:") as archive:
        for entry in archive:
            meaningful_size = max(
                meaningful_size,
                entry.offset_data + ((entry.size + 511) // 512) * 512,
            )
    fragment = raw_tar[:meaningful_size]
    if terminal:
        fragment += bytes(1024)
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="",
        mode="wb",
        fileobj=compressed,
        mtime=0,
        compresslevel=compresslevel,
    ) as gzip_file:
        gzip_file.write(fragment)
    return compressed.getvalue()


def nexus_compatible_tar_gzip(
    entries: list[tuple[str, bytes, int]], timestamp: int, *, terminal: bool
) -> bytes:
    """Avoid false gzip boundaries in Nexus 3.94's APK control checksum scanner."""
    for compresslevel in range(9, -1, -1):
        for timestamp_offset in range(64):
            member = tar_gzip(
                entries,
                timestamp + timestamp_offset,
                terminal=terminal,
                compresslevel=compresslevel,
            )
            if GZIP_MAGIC not in member[2:]:
                return member
    raise RuntimeError("could not encode APK member without an embedded gzip header marker")


def package_bytes(
    name: str,
    version: str,
    architecture: str,
    message: str,
    dependencies: list[str],
    timestamp: int,
    payload_size: int,
    signing_key: pathlib.Path | None,
    signature_key_name: str | None,
) -> tuple[bytes, str, str]:
    marker_path = f"usr/share/kkrepo-alpine-e2e/{name}.txt"
    marker = (message + "\n").encode()
    if payload_size:
        seed = marker
        generated = bytearray()
        counter = 0
        while len(generated) < payload_size:
            generated.extend(hashlib.sha256(seed + counter.to_bytes(8, "big")).digest())
            counter += 1
        marker = bytes(generated[:payload_size])
    data_member = tar_gzip([
        ("usr/", b"", 0o755),
        ("usr/share/", b"", 0o755),
        ("usr/share/kkrepo-alpine-e2e/", b"", 0o755),
        (marker_path, marker, 0o644),
    ], timestamp, terminal=True)
    data_sha256 = hashlib.sha256(data_member).hexdigest()
    fields = [
        "# Generated by kkRepo Alpine client E2E",
        f"pkgname = {name}",
        f"pkgver = {version}",
        "pkgdesc = kkRepo Alpine client E2E fixture",
        f"url = https://kkrepo.invalid/alpine/{name}",
        f"builddate = {timestamp}",
        "packager = kkRepo E2E <e2e@kkrepo.invalid>",
        f"size = {len(marker)}",
        f"arch = {architecture}",
        f"origin = {name}",
        "maintainer = kkRepo E2E <e2e@kkrepo.invalid>",
        "license = MIT",
    ]
    fields.extend(f"depend = {dependency}" for dependency in dependencies)
    fields.append(f"datahash = {data_sha256}")
    pkginfo = ("\n".join(fields) + "\n").encode()
    control_member = nexus_compatible_tar_gzip(
        [(".PKGINFO", pkginfo, 0o644)], timestamp, terminal=False
    )
    signature_member = b""
    if signing_key is not None and signature_key_name is not None:
        signature = subprocess.run(
            ["openssl", "dgst", "-sha1", "-sign", str(signing_key)],
            input=control_member,
            stdout=subprocess.PIPE,
            check=True,
        ).stdout
        signature_member = nexus_compatible_tar_gzip(
            [(f".SIGN.RSA.{signature_key_name}", signature, 0o644)],
            timestamp,
            terminal=False,
        )
    identity = "Q1" + __import__("base64").b64encode(
        hashlib.sha1(control_member).digest()
    ).decode("ascii")
    return signature_member + control_member + data_member, identity, marker_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--package", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--architecture", default="noarch")
    parser.add_argument("--message", default="kkRepo Alpine client E2E")
    parser.add_argument("--depends", action="append", default=[])
    parser.add_argument("--timestamp", type=int, default=1_786_665_600)
    parser.add_argument("--payload-size", type=int, default=0)
    parser.add_argument("--signing-key", type=pathlib.Path)
    parser.add_argument("--signature-key-name")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not PACKAGE_RE.fullmatch(args.package):
        raise SystemExit(f"invalid Alpine package name: {args.package}")
    if not VERSION_RE.fullmatch(args.version):
        raise SystemExit(f"invalid Alpine package version: {args.version}")
    if not ARCH_RE.fullmatch(args.architecture):
        raise SystemExit(f"invalid Alpine architecture: {args.architecture}")
    if args.timestamp < 0:
        raise SystemExit("timestamp must be non-negative")
    if args.payload_size < 0:
        raise SystemExit("payload size must be non-negative")
    if (args.signing_key is None) != (args.signature_key_name is None):
        raise SystemExit("--signing-key and --signature-key-name must be provided together")
    if args.signing_key is not None and not args.signing_key.is_file():
        raise SystemExit(f"Alpine signing key does not exist: {args.signing_key}")
    if args.signature_key_name is not None and not re.fullmatch(
        r"[A-Za-z0-9][A-Za-z0-9._-]{0,190}", args.signature_key_name
    ):
        raise SystemExit(f"invalid Alpine signature key name: {args.signature_key_name}")
    payload, identity, marker_path = package_bytes(
        args.package,
        args.version,
        args.architecture,
        args.message,
        args.depends,
        args.timestamp,
        args.payload_size,
        args.signing_key,
        args.signature_key_name,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(payload)
    print(json.dumps({
        "package": args.package,
        "version": args.version,
        "architecture": args.architecture,
        "filename": args.output.name,
        "size": len(payload),
        "sha256": hashlib.sha256(payload).hexdigest(),
        "identity": identity,
        "markerPath": marker_path,
        "message": args.message,
    }, sort_keys=True))


if __name__ == "__main__":
    main()
