-- PostgreSQL 12+ baseline equivalent to the MySQL V29 logical schema.
-- MySQL V1-V29 remain frozen in the mysql migration directory; shared versions start at V30.

CREATE FUNCTION kkrepo_set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE SPRING_SESSION (
  PRIMARY_ID CHAR(36) NOT NULL,
  SESSION_ID CHAR(36) NOT NULL,
  CREATION_TIME BIGINT NOT NULL,
  LAST_ACCESS_TIME BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INTEGER NOT NULL,
  EXPIRY_TIME BIGINT NOT NULL,
  PRINCIPAL_NAME VARCHAR(100),
  CONSTRAINT pk_spring_session PRIMARY KEY (PRIMARY_ID)
);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID CHAR(36) NOT NULL,
  ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
  ATTRIBUTE_BYTES BYTEA NOT NULL,
  CONSTRAINT pk_spring_session_attributes PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME)
);

CREATE TABLE api_key (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  domain VARCHAR(100) NOT NULL,
  owner_source VARCHAR(100) NOT NULL,
  owner_user_id VARCHAR(255) NOT NULL,
  display_name VARCHAR(255),
  status VARCHAR(50) DEFAULT 'ACTIVE' NOT NULL,
  api_key_hash VARCHAR(255) NOT NULL,
  token_prefix VARCHAR(32),
  scopes_json JSONB,
  encrypted_payload TEXT NOT NULL,
  expires_at TIMESTAMP(3) WITHOUT TIME ZONE,
  last_used_at TIMESTAMP(3) WITHOUT TIME ZONE,
  created_at TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_api_key PRIMARY KEY (id)
);

CREATE TABLE asset (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  component_id BIGINT CHECK (component_id >= 0),
  asset_blob_id BIGINT CHECK (asset_blob_id >= 0),
  format VARCHAR(50) NOT NULL,
  path VARCHAR(2048) NOT NULL,
  path_hash BYTEA NOT NULL,
  name VARCHAR(512) NOT NULL,
  kind VARCHAR(50),
  content_type VARCHAR(255),
  size BIGINT CHECK (size >= 0),
  last_downloaded_at TIMESTAMPTZ(3),
  last_updated_at TIMESTAMPTZ(3),
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_asset PRIMARY KEY (id)
);

CREATE TABLE asset_blob (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  blob_store_id BIGINT NOT NULL CHECK (blob_store_id >= 0),
  blob_ref VARCHAR(1024) NOT NULL,
  blob_ref_hash BYTEA NOT NULL,
  object_key VARCHAR(2048) NOT NULL,
  object_key_hash BYTEA NOT NULL,
  sha1 CHAR(40),
  sha256 CHAR(64),
  md5 CHAR(32),
  size BIGINT NOT NULL CHECK (size >= 0),
  content_type VARCHAR(255),
  created_by VARCHAR(255),
  created_by_ip VARCHAR(64),
  blob_created_at TIMESTAMPTZ(3),
  blob_updated_at TIMESTAMPTZ(3),
  deleted_at TIMESTAMPTZ(3),
  delete_reason VARCHAR(255),
  delete_claimed_at TIMESTAMPTZ(3),
  attributes_json JSONB,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_asset_blob PRIMARY KEY (id)
);

CREATE TABLE auth_ticket (
  token_hash CHAR(64) NOT NULL,
  payload TEXT NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_auth_ticket PRIMARY KEY (token_hash)
);

CREATE TABLE blob_store (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  name VARCHAR(200) NOT NULL,
  type VARCHAR(50) NOT NULL,
  endpoint VARCHAR(512),
  region VARCHAR(100),
  bucket VARCHAR(255),
  prefix VARCHAR(512),
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_blob_store PRIMARY KEY (id)
);

CREATE TABLE browse_node (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  parent_id BIGINT CHECK (parent_id >= 0),
  component_id BIGINT CHECK (component_id >= 0),
  asset_id BIGINT CHECK (asset_id >= 0),
  path VARCHAR(2048) NOT NULL,
  path_hash BYTEA NOT NULL,
  display_name VARCHAR(512) NOT NULL,
  package_url VARCHAR(2048),
  depth INTEGER DEFAULT 0 NOT NULL,
  has_asset_subtree BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_browse_node PRIMARY KEY (id)
);

CREATE TABLE cache_version (
  name VARCHAR(128) NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_cache_version PRIMARY KEY (name)
);

CREATE TABLE cleanup_policy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  name VARCHAR(200) NOT NULL,
  format VARCHAR(50) NOT NULL,
  mode VARCHAR(50) NOT NULL,
  notes VARCHAR(2048),
  criteria_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_cleanup_policy PRIMARY KEY (id)
);

CREATE TABLE component (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  format VARCHAR(50) NOT NULL,
  namespace VARCHAR(512),
  name VARCHAR(512) NOT NULL,
  version VARCHAR(255),
  kind VARCHAR(50),
  coordinate_hash BYTEA NOT NULL,
  attributes_json JSONB NOT NULL,
  last_updated_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_component PRIMARY KEY (id)
);

CREATE TABLE component_search (
  component_id BIGINT NOT NULL CHECK (component_id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  format VARCHAR(50) NOT NULL,
  namespace VARCHAR(512),
  name VARCHAR(512) NOT NULL,
  version VARCHAR(255),
  keywords TEXT NOT NULL,
  refreshed_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector(
      'simple',
      translate(
        COALESCE(namespace, '') || ' ' || name || ' ' || COALESCE(version, '') || ' ' || keywords,
        '.-@/_',
        '     '))
  ) STORED,
  CONSTRAINT pk_component_search PRIMARY KEY (component_id)
);

CREATE TABLE content_selector (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  name VARCHAR(200) NOT NULL,
  type VARCHAR(50) NOT NULL,
  description VARCHAR(1024),
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_content_selector PRIMARY KEY (id)
);

CREATE TABLE docker_auth_token (
  token_hash CHAR(64) NOT NULL,
  subject_source VARCHAR(100) NOT NULL,
  subject_user_id VARCHAR(255) NOT NULL,
  subject_realm_id VARCHAR(255),
  subject_api_key_id BIGINT CHECK (subject_api_key_id >= 0),
  scopes_json JSONB NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_docker_auth_token PRIMARY KEY (token_hash)
);

CREATE TABLE docker_manifest (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  image_name VARCHAR(255) NOT NULL,
  image_name_hash BYTEA NOT NULL,
  digest_algorithm VARCHAR(32) NOT NULL,
  digest VARCHAR(255) NOT NULL,
  digest_hash BYTEA NOT NULL,
  media_type VARCHAR(255) NOT NULL,
  artifact_type VARCHAR(255),
  subject_digest VARCHAR(255),
  subject_digest_hash BYTEA,
  asset_id BIGINT NOT NULL CHECK (asset_id >= 0),
  size BIGINT NOT NULL CHECK (size >= 0),
  pushed_by VARCHAR(255),
  pushed_by_ip VARCHAR(64),
  deleted_at TIMESTAMPTZ(3),
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_docker_manifest PRIMARY KEY (id)
);

CREATE TABLE docker_manifest_reference (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  manifest_id BIGINT NOT NULL CHECK (manifest_id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  image_name VARCHAR(255) NOT NULL,
  digest VARCHAR(255) NOT NULL,
  digest_hash BYTEA NOT NULL,
  reference_kind VARCHAR(32) NOT NULL,
  media_type VARCHAR(255),
  size BIGINT CHECK (size >= 0),
  platform_json JSONB,
  annotations_json JSONB,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_docker_manifest_reference PRIMARY KEY (id)
);

CREATE TABLE docker_tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  image_name VARCHAR(255) NOT NULL,
  image_name_hash BYTEA NOT NULL,
  tag VARCHAR(128) NOT NULL,
  tag_hash BYTEA NOT NULL,
  manifest_id BIGINT NOT NULL CHECK (manifest_id >= 0),
  manifest_digest VARCHAR(255) NOT NULL,
  pushed_by VARCHAR(255),
  pushed_by_ip VARCHAR(64),
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_docker_tag PRIMARY KEY (id)
);

CREATE TABLE docker_upload_chunk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  session_uuid VARCHAR(64) NOT NULL,
  chunk_index INTEGER NOT NULL,
  start_offset BIGINT NOT NULL CHECK (start_offset >= 0),
  end_offset BIGINT NOT NULL CHECK (end_offset >= 0),
  blob_ref VARCHAR(1024),
  object_key VARCHAR(2048),
  sha256 CHAR(64) NOT NULL,
  size BIGINT NOT NULL CHECK (size >= 0),
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_docker_upload_chunk PRIMARY KEY (id)
);

CREATE TABLE docker_upload_session (
  uuid VARCHAR(64) NOT NULL,
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  image_name VARCHAR(255) NOT NULL,
  image_name_hash BYTEA NOT NULL,
  status VARCHAR(32) NOT NULL,
  next_offset BIGINT DEFAULT 0 NOT NULL CHECK (next_offset >= 0),
  digest_algorithm VARCHAR(32),
  expected_digest VARCHAR(255),
  created_by VARCHAR(255),
  created_by_ip VARCHAR(64),
  expires_at TIMESTAMPTZ(3) NOT NULL,
  locked_by VARCHAR(255),
  locked_until TIMESTAMPTZ(3),
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_docker_upload_session PRIMARY KEY (uuid)
);

CREATE TABLE maintenance_cursor (
  task_name VARCHAR(100) NOT NULL,
  last_seen_id BIGINT DEFAULT 0 NOT NULL CHECK (last_seen_id >= 0),
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_maintenance_cursor PRIMARY KEY (task_name)
);

CREATE TABLE metadata_rebuild_marker (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  scope_key VARCHAR(512) NOT NULL,
  requested_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  attempts INTEGER DEFAULT 0 NOT NULL,
  last_attempted_at TIMESTAMPTZ(3),
  last_error TEXT,
  CONSTRAINT pk_metadata_rebuild_marker PRIMARY KEY (repository_id, scope_key)
);

CREATE TABLE migration_checkpoint (
  job_id BIGINT NOT NULL CHECK (job_id >= 0),
  source_database VARCHAR(100) NOT NULL,
  source_class VARCHAR(200) NOT NULL,
  source_rid VARCHAR(100) NOT NULL,
  target_table VARCHAR(200) NOT NULL,
  target_id VARCHAR(255) NOT NULL,
  source_checksum CHAR(64),
  migrated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_migration_checkpoint PRIMARY KEY (job_id, source_database, source_class, source_rid)
);

CREATE TABLE migration_job (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  source_nexus_version VARCHAR(100) NOT NULL,
  source_data_path VARCHAR(2048) NOT NULL,
  status VARCHAR(50) NOT NULL,
  options_json JSONB NOT NULL,
  summary_json JSONB,
  started_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  finished_at TIMESTAMPTZ(3),
  CONSTRAINT pk_migration_job PRIMARY KEY (id)
);

CREATE TABLE migration_validation_result (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  job_id BIGINT NOT NULL CHECK (job_id >= 0),
  scope VARCHAR(200) NOT NULL,
  source_count BIGINT CHECK (source_count >= 0),
  target_count BIGINT CHECK (target_count >= 0),
  status VARCHAR(50) NOT NULL,
  details_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_migration_validation_result PRIMARY KEY (id)
);

CREATE TABLE proxy_remote_state (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  blocked_until TIMESTAMPTZ(3),
  fail_count INTEGER DEFAULT 0 NOT NULL,
  last_success_at TIMESTAMPTZ(3),
  last_failure_at TIMESTAMPTZ(3),
  last_error VARCHAR(1024),
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_proxy_remote_state PRIMARY KEY (repository_id)
);

CREATE TABLE pub_upload_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  session_id VARCHAR(128) NOT NULL,
  field_token VARCHAR(128) NOT NULL,
  principal_user_id VARCHAR(255),
  principal_api_key_id BIGINT CHECK (principal_api_key_id >= 0),
  status VARCHAR(32) NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  blob_store_id BIGINT CHECK (blob_store_id >= 0),
  blob_ref VARCHAR(1024),
  object_key VARCHAR(2048),
  md5 CHAR(32),
  sha1 CHAR(40),
  sha256 CHAR(64),
  sha512 CHAR(128),
  size BIGINT CHECK (size >= 0),
  package_name VARCHAR(128),
  version VARCHAR(255),
  pubspec_json JSONB,
  error_message VARCHAR(2048),
  finalized_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_pub_upload_session PRIMARY KEY (id)
);

CREATE TABLE repository (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  name VARCHAR(200) NOT NULL,
  format VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  recipe_name VARCHAR(100) NOT NULL,
  online BOOLEAN DEFAULT true NOT NULL,
  blob_store_id BIGINT CHECK (blob_store_id >= 0),
  routing_rule_id BIGINT CHECK (routing_rule_id >= 0),
  proxy_remote_url VARCHAR(1024),
  version_policy VARCHAR(50),
  layout_policy VARCHAR(50),
  write_policy VARCHAR(50),
  strict_content_type_validation BOOLEAN DEFAULT true NOT NULL,
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_repository PRIMARY KEY (id)
);

CREATE TABLE repository_cleanup_policy (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  cleanup_policy_id BIGINT NOT NULL CHECK (cleanup_policy_id >= 0),
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_repository_cleanup_policy PRIMARY KEY (repository_id, cleanup_policy_id)
);

CREATE TABLE repository_data_migration_asset (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  repository_job_id BIGINT NOT NULL CHECK (repository_job_id >= 0),
  source_asset_id VARCHAR(100),
  source_component_id VARCHAR(100),
  source_path VARCHAR(2048) NOT NULL,
  source_path_hash BYTEA NOT NULL,
  format VARCHAR(50) NOT NULL,
  namespace VARCHAR(512),
  name VARCHAR(512),
  version VARCHAR(255),
  asset_kind VARCHAR(100),
  content_type VARCHAR(255),
  size BIGINT CHECK (size >= 0),
  source_blob_ref VARCHAR(1024),
  source_last_updated_at TIMESTAMPTZ(3),
  source_last_downloaded_at TIMESTAMPTZ(3),
  source_blob_created_at TIMESTAMPTZ(3),
  source_blob_updated_at TIMESTAMPTZ(3),
  source_created_by VARCHAR(255),
  source_created_by_ip VARCHAR(64),
  status VARCHAR(50) NOT NULL,
  attempts INTEGER DEFAULT 0 NOT NULL CHECK (attempts >= 0),
  claimed_at TIMESTAMPTZ(3),
  migrated_at TIMESTAMPTZ(3),
  target_component_id BIGINT CHECK (target_component_id >= 0),
  target_asset_id BIGINT CHECK (target_asset_id >= 0),
  target_asset_blob_id BIGINT CHECK (target_asset_blob_id >= 0),
  last_error TEXT,
  metadata_json JSONB NOT NULL,
  discovered_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_repository_data_migration_asset PRIMARY KEY (id)
);

CREATE TABLE repository_data_migration_repository (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  migration_job_id BIGINT NOT NULL CHECK (migration_job_id >= 0),
  source_repository_name VARCHAR(255) NOT NULL,
  target_repository_name VARCHAR(255) NOT NULL,
  target_repository_id BIGINT NOT NULL CHECK (target_repository_id >= 0),
  format VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  cursor_path VARCHAR(2048),
  page_size INTEGER NOT NULL CHECK (page_size >= 0),
  total_assets BIGINT DEFAULT 0 NOT NULL CHECK (total_assets >= 0),
  discovered_assets BIGINT DEFAULT 0 NOT NULL CHECK (discovered_assets >= 0),
  migrated_assets BIGINT DEFAULT 0 NOT NULL CHECK (migrated_assets >= 0),
  failed_assets BIGINT DEFAULT 0 NOT NULL CHECK (failed_assets >= 0),
  claimed_at TIMESTAMPTZ(3),
  last_error TEXT,
  options_json JSONB NOT NULL,
  started_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  finished_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_repository_data_migration_repository PRIMARY KEY (id)
);

CREATE TABLE repository_index_rebuild_marker (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  index_kind VARCHAR(50) NOT NULL,
  scope_key VARCHAR(512) DEFAULT '' NOT NULL,
  requested_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  attempts INTEGER DEFAULT 0 NOT NULL,
  last_attempted_at TIMESTAMPTZ(3),
  last_error TEXT,
  CONSTRAINT pk_repository_index_rebuild_marker PRIMARY KEY (repository_id, index_kind, scope_key)
);

CREATE TABLE repository_member (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  member_repository_id BIGINT NOT NULL CHECK (member_repository_id >= 0),
  sort_order INTEGER NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_repository_member PRIMARY KEY (repository_id, member_repository_id)
);

CREATE TABLE routing_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  name VARCHAR(200) NOT NULL,
  mode VARCHAR(32) NOT NULL,
  description VARCHAR(1024),
  matchers_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_routing_rule PRIMARY KEY (id)
);

CREATE TABLE security_anonymous_config (
  id SMALLINT NOT NULL CHECK (id >= 0),
  enabled BOOLEAN NOT NULL,
  user_source VARCHAR(100) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  realm_name VARCHAR(255) NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_anonymous_config PRIMARY KEY (id)
);

CREATE TABLE security_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  occurred_at TIMESTAMP(3) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  actor_source VARCHAR(100),
  actor_user_id VARCHAR(255),
  actor_realm_id VARCHAR(100),
  actor_api_key_id BIGINT CHECK (actor_api_key_id >= 0),
  remote_addr VARCHAR(100),
  method VARCHAR(16) NOT NULL,
  path VARCHAR(2048) NOT NULL,
  permission VARCHAR(512),
  status INTEGER,
  outcome VARCHAR(50) NOT NULL,
  details_json JSONB,
  CONSTRAINT pk_security_audit_log PRIMARY KEY (id)
);

CREATE TABLE security_privilege (
  privilege_id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1024),
  type VARCHAR(100) NOT NULL,
  read_only BOOLEAN DEFAULT false NOT NULL,
  properties_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_privilege PRIMARY KEY (privilege_id)
);

CREATE TABLE security_realm (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  realm_id VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  enabled BOOLEAN DEFAULT false NOT NULL,
  priority INTEGER DEFAULT 0 NOT NULL,
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_realm PRIMARY KEY (id)
);

CREATE TABLE security_realm_config (
  id SMALLINT NOT NULL CHECK (id >= 0),
  realms_json JSONB NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_realm_config PRIMARY KEY (id)
);

CREATE TABLE security_repository_target (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  target_id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  format VARCHAR(50) NOT NULL,
  content_expression TEXT,
  path_patterns_json JSONB NOT NULL,
  attributes_json JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_repository_target PRIMARY KEY (id)
);

CREATE TABLE security_role (
  role_id VARCHAR(255) NOT NULL,
  source VARCHAR(100) DEFAULT 'default' NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1024),
  read_only BOOLEAN DEFAULT false NOT NULL,
  attributes_json JSONB,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_role PRIMARY KEY (role_id)
);

CREATE TABLE security_role_inheritance (
  role_id VARCHAR(255) NOT NULL,
  child_role_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_role_inheritance PRIMARY KEY (role_id, child_role_id)
);

CREATE TABLE security_role_privilege (
  role_id VARCHAR(255) NOT NULL,
  privilege_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_role_privilege PRIMARY KEY (role_id, privilege_id)
);

CREATE TABLE security_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  source VARCHAR(100) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  email VARCHAR(512),
  password_hash VARCHAR(1024),
  status VARCHAR(50) NOT NULL,
  external_id VARCHAR(255),
  attributes_json JSONB,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_user PRIMARY KEY (id)
);

CREATE TABLE security_user_role (
  user_id BIGINT NOT NULL CHECK (user_id >= 0),
  role_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_security_user_role PRIMARY KEY (user_id, role_id)
);

CREATE TABLE ui_settings (
  id SMALLINT NOT NULL CHECK (id >= 0),
  default_language VARCHAR(20) NOT NULL,
  updated_at TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT pk_ui_settings PRIMARY KEY (id)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
CREATE INDEX idx_api_key_hash ON api_key (api_key_hash);
CREATE UNIQUE INDEX uk_api_key_domain_hash ON api_key (domain, api_key_hash);
CREATE UNIQUE INDEX uk_api_key_domain_owner ON api_key (domain, owner_source, owner_user_id);
CREATE INDEX idx_asset_blob ON asset (asset_blob_id);
CREATE INDEX idx_asset_component ON asset (component_id);
CREATE INDEX idx_asset_component_path ON asset (component_id, (left(path, 191)));
CREATE INDEX idx_asset_name ON asset (format, (left(name, 191)));
CREATE INDEX idx_asset_repo_format_kind_path ON asset (repository_id, format, kind, (left(path, 191)));
CREATE INDEX idx_asset_repository_format ON asset (repository_id, format);
CREATE INDEX idx_asset_repository_kind ON asset (repository_id, kind);
CREATE INDEX idx_asset_repository_path_prefix ON asset (repository_id, (left(path, 191)));
CREATE UNIQUE INDEX uk_asset_path ON asset (repository_id, path_hash);
CREATE INDEX idx_asset_blob_checksum_sha1 ON asset_blob (sha1);
CREATE INDEX idx_asset_blob_checksum_sha256 ON asset_blob (sha256);
CREATE INDEX idx_asset_blob_delete_claimed_at ON asset_blob (delete_claimed_at);
CREATE INDEX idx_asset_blob_deleted_at ON asset_blob (deleted_at);
CREATE INDEX idx_asset_blob_reusable ON asset_blob (blob_store_id, sha256, size, deleted_at);
CREATE INDEX idx_asset_blob_usage ON asset_blob (blob_store_id, deleted_at, size);
CREATE UNIQUE INDEX uk_asset_blob_object ON asset_blob (blob_store_id, object_key_hash);
CREATE UNIQUE INDEX uk_asset_blob_ref ON asset_blob (blob_store_id, blob_ref_hash);
CREATE INDEX idx_auth_ticket_expires_at ON auth_ticket (expires_at);
CREATE UNIQUE INDEX uk_blob_store_name ON blob_store (name);
CREATE INDEX idx_browse_node_component ON browse_node (component_id);
CREATE INDEX idx_browse_node_parent ON browse_node (parent_id);
CREATE INDEX idx_browse_node_parent_subtree ON browse_node (parent_id, has_asset_subtree);
CREATE INDEX idx_browse_node_root ON browse_node (repository_id, depth, path_hash);
CREATE UNIQUE INDEX uk_browse_node_asset ON browse_node (asset_id);
CREATE UNIQUE INDEX uk_browse_node_path ON browse_node (repository_id, path_hash);
CREATE INDEX idx_cleanup_policy_format ON cleanup_policy (format);
CREATE UNIQUE INDEX uk_cleanup_policy_name ON cleanup_policy (name);
CREATE INDEX idx_component_format_last_updated ON component (format, last_updated_at);
CREATE INDEX idx_component_last_updated ON component (last_updated_at);
CREATE INDEX idx_component_name_version ON component (format, (left(name, 191)), version);
CREATE INDEX idx_component_repo_format_updated ON component (repository_id, format, last_updated_at);
CREATE INDEX idx_component_repo_name ON component (repository_id, (left(name, 191)));
CREATE INDEX idx_component_repo_ns_name ON component (repository_id, (left(namespace, 191)), (left(name, 191)));
CREATE INDEX idx_component_repository_format ON component (repository_id, format);
CREATE UNIQUE INDEX uk_component_coordinate ON component (repository_id, coordinate_hash);
CREATE INDEX idx_component_search_repository ON component_search (repository_id);
CREATE UNIQUE INDEX uk_content_selector_name ON content_selector (name);
CREATE INDEX idx_docker_auth_token_expires ON docker_auth_token (expires_at);
CREATE INDEX idx_docker_manifest_asset ON docker_manifest (asset_id);
CREATE INDEX idx_docker_manifest_image_updated ON docker_manifest (repository_id, image_name_hash, updated_at);
CREATE INDEX idx_docker_manifest_subject ON docker_manifest (repository_id, subject_digest_hash);
CREATE UNIQUE INDEX uk_docker_manifest_digest ON docker_manifest (repository_id, image_name_hash, digest_hash);
CREATE INDEX idx_docker_reference_digest ON docker_manifest_reference (repository_id, digest_hash);
CREATE INDEX idx_docker_reference_manifest_kind ON docker_manifest_reference (manifest_id, reference_kind);
CREATE INDEX idx_docker_tag_image_tag ON docker_tag (repository_id, image_name_hash, tag);
CREATE INDEX idx_docker_tag_manifest ON docker_tag (manifest_id);
CREATE UNIQUE INDEX uk_docker_tag ON docker_tag (repository_id, image_name_hash, tag_hash);
CREATE INDEX idx_docker_upload_chunk_session ON docker_upload_chunk (session_uuid, start_offset);
CREATE UNIQUE INDEX uk_docker_upload_chunk ON docker_upload_chunk (session_uuid, chunk_index);
CREATE INDEX idx_docker_upload_expires ON docker_upload_session (expires_at);
CREATE INDEX idx_docker_upload_repository ON docker_upload_session (repository_id, image_name_hash, status);
CREATE INDEX idx_metadata_rebuild_marker_requested_at ON metadata_rebuild_marker (requested_at);
CREATE INDEX idx_migration_checkpoint_target ON migration_checkpoint (target_table, target_id);
CREATE INDEX idx_migration_job_status ON migration_job (status);
CREATE INDEX idx_migration_validation_job_scope ON migration_validation_result (job_id, scope);
CREATE INDEX fk_pub_upload_session_blob_store ON pub_upload_session (blob_store_id);
CREATE INDEX idx_pub_upload_session_repository_package ON pub_upload_session (repository_id, package_name, version);
CREATE INDEX idx_pub_upload_session_status_expires ON pub_upload_session (status, expires_at);
CREATE UNIQUE INDEX uk_pub_upload_session ON pub_upload_session (repository_id, session_id);
CREATE INDEX idx_repository_blob_store ON repository (blob_store_id);
CREATE INDEX idx_repository_format_type ON repository (format, type);
CREATE INDEX idx_repository_routing_rule ON repository (routing_rule_id);
CREATE UNIQUE INDEX uk_repository_name ON repository (name);
CREATE INDEX idx_repository_cleanup_policy_policy ON repository_cleanup_policy (cleanup_policy_id);
CREATE INDEX fk_repo_data_migration_asset_component ON repository_data_migration_asset (target_component_id);
CREATE INDEX idx_repo_data_migration_asset_repo_status ON repository_data_migration_asset (repository_job_id, status, id);
CREATE INDEX idx_repo_data_migration_asset_status ON repository_data_migration_asset (status, claimed_at, id);
CREATE INDEX idx_repo_data_migration_asset_target_asset ON repository_data_migration_asset (target_asset_id);
CREATE INDEX idx_repo_data_migration_asset_target_blob ON repository_data_migration_asset (target_asset_blob_id);
CREATE UNIQUE INDEX uk_repo_data_migration_asset_path ON repository_data_migration_asset (repository_job_id, source_path_hash);
CREATE INDEX idx_repo_data_migration_status ON repository_data_migration_repository (status, claimed_at, id);
CREATE INDEX idx_repo_data_migration_target ON repository_data_migration_repository (target_repository_id);
CREATE UNIQUE INDEX uk_repo_data_migration_source ON repository_data_migration_repository (migration_job_id, source_repository_name);
CREATE INDEX idx_repository_index_rebuild_requested_at ON repository_index_rebuild_marker (requested_at);
CREATE INDEX idx_repository_member_target ON repository_member (member_repository_id);
CREATE UNIQUE INDEX uk_repository_member_order ON repository_member (repository_id, sort_order);
CREATE UNIQUE INDEX uk_routing_rule_name ON routing_rule (name);
CREATE INDEX idx_security_audit_log_actor ON security_audit_log (actor_source, actor_user_id);
CREATE INDEX idx_security_audit_log_method_time ON security_audit_log (method, occurred_at);
CREATE INDEX idx_security_audit_log_occurred_at ON security_audit_log (occurred_at);
CREATE INDEX idx_security_audit_log_outcome_status_time ON security_audit_log (outcome, status, occurred_at);
CREATE INDEX idx_security_audit_log_path ON security_audit_log ((left(path, 255)));
CREATE INDEX idx_security_privilege_type ON security_privilege (type);
CREATE UNIQUE INDEX uk_security_privilege_name ON security_privilege (name);
CREATE INDEX idx_security_realm_enabled_priority ON security_realm (enabled, priority);
CREATE UNIQUE INDEX uk_security_realm_id ON security_realm (realm_id);
CREATE INDEX idx_security_repository_target_format ON security_repository_target (format);
CREATE UNIQUE INDEX uk_security_repository_target_id ON security_repository_target (target_id);
CREATE INDEX idx_security_role_name ON security_role (name);
CREATE INDEX idx_security_role_inheritance_child ON security_role_inheritance (child_role_id);
CREATE INDEX idx_security_role_privilege_privilege ON security_role_privilege (privilege_id);
CREATE INDEX idx_security_user_email ON security_user ((left(email, 191)));
CREATE UNIQUE INDEX uk_security_user_source_user ON security_user (source, user_id);
CREATE INDEX idx_security_user_role_role ON security_user_role (role_id);
CREATE INDEX ft_component_search ON component_search USING GIN (search_vector);
CREATE UNIQUE INDEX uk_repository_docker_connector_port
  ON repository (((attributes_json #>> '{docker,connectorPort}')::integer))
  WHERE format = 'docker'
    AND COALESCE((attributes_json #>> '{docker,connectorEnabled}')::boolean, true);

ALTER TABLE SPRING_SESSION_ATTRIBUTES ADD CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE;
ALTER TABLE asset ADD CONSTRAINT fk_asset_blob FOREIGN KEY (asset_blob_id) REFERENCES asset_blob (id) ON DELETE SET NULL;
ALTER TABLE asset ADD CONSTRAINT fk_asset_component FOREIGN KEY (component_id) REFERENCES component (id) ON DELETE SET NULL;
ALTER TABLE asset ADD CONSTRAINT fk_asset_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE asset_blob ADD CONSTRAINT fk_asset_blob_blob_store FOREIGN KEY (blob_store_id) REFERENCES blob_store (id) ON DELETE RESTRICT;
ALTER TABLE browse_node ADD CONSTRAINT fk_browse_node_asset FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE SET NULL;
ALTER TABLE browse_node ADD CONSTRAINT fk_browse_node_component FOREIGN KEY (component_id) REFERENCES component (id) ON DELETE SET NULL;
ALTER TABLE browse_node ADD CONSTRAINT fk_browse_node_parent FOREIGN KEY (parent_id) REFERENCES browse_node (id) ON DELETE CASCADE;
ALTER TABLE browse_node ADD CONSTRAINT fk_browse_node_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE component ADD CONSTRAINT fk_component_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE component_search ADD CONSTRAINT fk_component_search_component FOREIGN KEY (component_id) REFERENCES component (id) ON DELETE CASCADE;
ALTER TABLE component_search ADD CONSTRAINT fk_component_search_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE docker_manifest ADD CONSTRAINT fk_docker_manifest_asset FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE;
ALTER TABLE docker_manifest ADD CONSTRAINT fk_docker_manifest_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE docker_manifest_reference ADD CONSTRAINT fk_docker_reference_manifest FOREIGN KEY (manifest_id) REFERENCES docker_manifest (id) ON DELETE CASCADE;
ALTER TABLE docker_manifest_reference ADD CONSTRAINT fk_docker_reference_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE docker_tag ADD CONSTRAINT fk_docker_tag_manifest FOREIGN KEY (manifest_id) REFERENCES docker_manifest (id) ON DELETE CASCADE;
ALTER TABLE docker_tag ADD CONSTRAINT fk_docker_tag_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE docker_upload_chunk ADD CONSTRAINT fk_docker_upload_chunk_session FOREIGN KEY (session_uuid) REFERENCES docker_upload_session (uuid) ON DELETE CASCADE;
ALTER TABLE docker_upload_session ADD CONSTRAINT fk_docker_upload_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE metadata_rebuild_marker ADD CONSTRAINT fk_metadata_rebuild_marker_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE migration_checkpoint ADD CONSTRAINT fk_migration_checkpoint_job FOREIGN KEY (job_id) REFERENCES migration_job (id) ON DELETE CASCADE;
ALTER TABLE migration_validation_result ADD CONSTRAINT fk_migration_validation_job FOREIGN KEY (job_id) REFERENCES migration_job (id) ON DELETE CASCADE;
ALTER TABLE proxy_remote_state ADD CONSTRAINT fk_proxy_remote_state_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE pub_upload_session ADD CONSTRAINT fk_pub_upload_session_blob_store FOREIGN KEY (blob_store_id) REFERENCES blob_store (id) ON DELETE SET NULL;
ALTER TABLE pub_upload_session ADD CONSTRAINT fk_pub_upload_session_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE repository ADD CONSTRAINT fk_repository_blob_store FOREIGN KEY (blob_store_id) REFERENCES blob_store (id) ON DELETE RESTRICT;
ALTER TABLE repository ADD CONSTRAINT fk_repository_routing_rule FOREIGN KEY (routing_rule_id) REFERENCES routing_rule (id) ON DELETE SET NULL;
ALTER TABLE repository_cleanup_policy ADD CONSTRAINT fk_repository_cleanup_policy_policy FOREIGN KEY (cleanup_policy_id) REFERENCES cleanup_policy (id) ON DELETE RESTRICT;
ALTER TABLE repository_cleanup_policy ADD CONSTRAINT fk_repository_cleanup_policy_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE repository_data_migration_asset ADD CONSTRAINT fk_repo_data_migration_asset_asset FOREIGN KEY (target_asset_id) REFERENCES asset (id) ON DELETE SET NULL;
ALTER TABLE repository_data_migration_asset ADD CONSTRAINT fk_repo_data_migration_asset_blob FOREIGN KEY (target_asset_blob_id) REFERENCES asset_blob (id) ON DELETE SET NULL;
ALTER TABLE repository_data_migration_asset ADD CONSTRAINT fk_repo_data_migration_asset_component FOREIGN KEY (target_component_id) REFERENCES component (id) ON DELETE SET NULL;
ALTER TABLE repository_data_migration_asset ADD CONSTRAINT fk_repo_data_migration_asset_repo FOREIGN KEY (repository_job_id) REFERENCES repository_data_migration_repository (id) ON DELETE CASCADE;
ALTER TABLE repository_data_migration_repository ADD CONSTRAINT fk_repo_data_migration_job FOREIGN KEY (migration_job_id) REFERENCES migration_job (id) ON DELETE CASCADE;
ALTER TABLE repository_data_migration_repository ADD CONSTRAINT fk_repo_data_migration_target FOREIGN KEY (target_repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE repository_index_rebuild_marker ADD CONSTRAINT fk_repository_index_rebuild_marker_repository FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE repository_member ADD CONSTRAINT fk_repository_member_group FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE;
ALTER TABLE repository_member ADD CONSTRAINT fk_repository_member_target FOREIGN KEY (member_repository_id) REFERENCES repository (id) ON DELETE RESTRICT;
ALTER TABLE security_role_inheritance ADD CONSTRAINT fk_security_role_inheritance_child FOREIGN KEY (child_role_id) REFERENCES security_role (role_id) ON DELETE CASCADE;
ALTER TABLE security_role_inheritance ADD CONSTRAINT fk_security_role_inheritance_role FOREIGN KEY (role_id) REFERENCES security_role (role_id) ON DELETE CASCADE;
ALTER TABLE security_role_privilege ADD CONSTRAINT fk_security_role_privilege_privilege FOREIGN KEY (privilege_id) REFERENCES security_privilege (privilege_id) ON DELETE CASCADE;
ALTER TABLE security_role_privilege ADD CONSTRAINT fk_security_role_privilege_role FOREIGN KEY (role_id) REFERENCES security_role (role_id) ON DELETE CASCADE;
ALTER TABLE security_user_role ADD CONSTRAINT fk_security_user_role_role FOREIGN KEY (role_id) REFERENCES security_role (role_id) ON DELETE CASCADE;
ALTER TABLE security_user_role ADD CONSTRAINT fk_security_user_role_user FOREIGN KEY (user_id) REFERENCES security_user (id) ON DELETE CASCADE;

ALTER TABLE ui_settings ADD CONSTRAINT ck_ui_settings_default_language
  CHECK (default_language IN ('browser', 'zh-CN', 'en'));
ALTER TABLE ui_settings ADD CONSTRAINT ck_ui_settings_singleton CHECK (id = 1);

CREATE TRIGGER trg_api_key_updated_at BEFORE UPDATE ON api_key
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_asset_updated_at BEFORE UPDATE ON asset
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_asset_blob_updated_at BEFORE UPDATE ON asset_blob
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_blob_store_updated_at BEFORE UPDATE ON blob_store
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_browse_node_updated_at BEFORE UPDATE ON browse_node
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_cache_version_updated_at BEFORE UPDATE ON cache_version
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_cleanup_policy_updated_at BEFORE UPDATE ON cleanup_policy
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_component_updated_at BEFORE UPDATE ON component
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_content_selector_updated_at BEFORE UPDATE ON content_selector
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_docker_manifest_updated_at BEFORE UPDATE ON docker_manifest
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_docker_tag_updated_at BEFORE UPDATE ON docker_tag
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_docker_upload_session_updated_at BEFORE UPDATE ON docker_upload_session
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_maintenance_cursor_updated_at BEFORE UPDATE ON maintenance_cursor
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_proxy_remote_state_updated_at BEFORE UPDATE ON proxy_remote_state
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_pub_upload_session_updated_at BEFORE UPDATE ON pub_upload_session
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_repository_updated_at BEFORE UPDATE ON repository
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_repository_data_migration_asset_updated_at BEFORE UPDATE ON repository_data_migration_asset
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_repository_data_migration_repository_updated_at BEFORE UPDATE ON repository_data_migration_repository
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_routing_rule_updated_at BEFORE UPDATE ON routing_rule
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_security_anonymous_config_updated_at BEFORE UPDATE ON security_anonymous_config
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_security_privilege_updated_at BEFORE UPDATE ON security_privilege
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_security_realm_updated_at BEFORE UPDATE ON security_realm
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_security_realm_config_updated_at BEFORE UPDATE ON security_realm_config
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_security_repository_target_updated_at BEFORE UPDATE ON security_repository_target
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_security_role_updated_at BEFORE UPDATE ON security_role
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_security_user_updated_at BEFORE UPDATE ON security_user
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();
CREATE TRIGGER trg_ui_settings_updated_at BEFORE UPDATE ON ui_settings
  FOR EACH ROW EXECUTE FUNCTION kkrepo_set_updated_at();

-- V29-equivalent built-in security and singleton seed data.
INSERT INTO maintenance_cursor (task_name, last_seen_id) VALUES ('blob_unreferenced_reconcile', 0);
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-all', 'nx-all', 'All Nexus permissions', 'wildcard', true, '{"pattern": "nexus:*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-apikey-all', 'nx-apikey-all', 'All permissions for APIKey', 'application', true, '{"domain": "apikey", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-blobstores-all', 'nx-blobstores-all', 'All permissions for Blob Stores', 'application', true, '{"domain": "blobstores", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-blobstores-create', 'nx-blobstores-create', 'Create permission for Blob Stores', 'application', true, '{"domain": "blobstores", "actions": "create,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-blobstores-delete', 'nx-blobstores-delete', 'Delete permission for Blob Stores', 'application', true, '{"domain": "blobstores", "actions": "delete,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-blobstores-read', 'nx-blobstores-read', 'Read permission for Blob Stores', 'application', true, '{"domain": "blobstores", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-blobstores-update', 'nx-blobstores-update', 'Update permission for Blob Stores', 'application', true, '{"domain": "blobstores", "actions": "update,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-bundles-all', 'nx-bundles-all', 'All permissions for Bundles', 'application', true, '{"domain": "bundles", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-bundles-read', 'nx-bundles-read', 'Read permission for Bundles', 'application', true, '{"domain": "bundles", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-component-upload', 'nx-component-upload', 'Upload component permission', 'application', true, '{"domain": "component", "actions": "create"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-healthcheck-read', 'nx-healthcheck-read', 'Read permission for Healthcheck', 'application', true, '{"domain": "healthcheck", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-ldap-all', 'nx-ldap-all', 'All permissions for LDAP', 'application', true, '{"domain": "ldap", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-ldap-create', 'nx-ldap-create', 'Create permission for LDAP', 'application', true, '{"domain": "ldap", "actions": "create,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-ldap-delete', 'nx-ldap-delete', 'Delete permission for LDAP', 'application', true, '{"domain": "ldap", "actions": "delete,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-ldap-read', 'nx-ldap-read', 'Read permission for LDAP', 'application', true, '{"domain": "ldap", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-ldap-update', 'nx-ldap-update', 'Update permission for LDAP', 'application', true, '{"domain": "ldap", "actions": "update,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-privileges-all', 'nx-privileges-all', 'All permissions for Privileges', 'application', true, '{"domain": "privileges", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-privileges-create', 'nx-privileges-create', 'Create permission for Privileges', 'application', true, '{"domain": "privileges", "actions": "create,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-privileges-delete', 'nx-privileges-delete', 'Delete permission for Privileges', 'application', true, '{"domain": "privileges", "actions": "delete,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-privileges-read', 'nx-privileges-read', 'Read permission for Privileges', 'application', true, '{"domain": "privileges", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-privileges-update', 'nx-privileges-update', 'Update permission for Privileges', 'application', true, '{"domain": "privileges", "actions": "update,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-admin-*-*-*', 'nx-repository-admin-*-*-*', 'All permissions for all repository administration', 'repository-admin', true, '{"format": "*", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-admin-*-*-add', 'nx-repository-admin-*-*-add', 'Add permission for all repository administration', 'repository-admin', true, '{"format": "*", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-admin-*-*-browse', 'nx-repository-admin-*-*-browse', 'Browse permission for all repository administration', 'repository-admin', true, '{"format": "*", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-admin-*-*-delete', 'nx-repository-admin-*-*-delete', 'Delete permission for all repository administration', 'repository-admin', true, '{"format": "*", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-admin-*-*-edit', 'nx-repository-admin-*-*-edit', 'Edit permission for all repository administration', 'repository-admin', true, '{"format": "*", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-admin-*-*-read', 'nx-repository-admin-*-*-read', 'Read permission for all repository administration', 'repository-admin', true, '{"format": "*", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-*-*-*', 'nx-repository-view-*-*-*', 'All permissions for all repository views', 'repository-view', true, '{"format": "*", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-*-*-add', 'nx-repository-view-*-*-add', 'Add permission for all repository views', 'repository-view', true, '{"format": "*", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-*-*-browse', 'nx-repository-view-*-*-browse', 'Browse permission for all repository views', 'repository-view', true, '{"format": "*", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-*-*-delete', 'nx-repository-view-*-*-delete', 'Delete permission for all repository views', 'repository-view', true, '{"format": "*", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-*-*-edit', 'nx-repository-view-*-*-edit', 'Edit permission for all repository views', 'repository-view', true, '{"format": "*", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-*-*-read', 'nx-repository-view-*-*-read', 'Read permission for all repository views', 'repository-view', true, '{"format": "*", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-go-*-*', 'nx-repository-view-go-*-*', 'All privileges for all ''go''-format repository views', 'repository-view', true, '{"format": "go", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-go-*-add', 'nx-repository-view-go-*-add', 'Add privilege for all ''go''-format repository views', 'repository-view', true, '{"format": "go", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-go-*-browse', 'nx-repository-view-go-*-browse', 'Browse privilege for all ''go''-format repository views', 'repository-view', true, '{"format": "go", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-go-*-delete', 'nx-repository-view-go-*-delete', 'Delete privilege for all ''go''-format repository views', 'repository-view', true, '{"format": "go", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-go-*-edit', 'nx-repository-view-go-*-edit', 'Edit privilege for all ''go''-format repository views', 'repository-view', true, '{"format": "go", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-go-*-read', 'nx-repository-view-go-*-read', 'Read privilege for all ''go''-format repository views', 'repository-view', true, '{"format": "go", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-helm-*-*', 'nx-repository-view-helm-*-*', 'All privileges for all ''helm''-format repository views', 'repository-view', true, '{"format": "helm", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-helm-*-add', 'nx-repository-view-helm-*-add', 'Add privilege for all ''helm''-format repository views', 'repository-view', true, '{"format": "helm", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-helm-*-browse', 'nx-repository-view-helm-*-browse', 'Browse privilege for all ''helm''-format repository views', 'repository-view', true, '{"format": "helm", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-helm-*-delete', 'nx-repository-view-helm-*-delete', 'Delete privilege for all ''helm''-format repository views', 'repository-view', true, '{"format": "helm", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-helm-*-edit', 'nx-repository-view-helm-*-edit', 'Edit privilege for all ''helm''-format repository views', 'repository-view', true, '{"format": "helm", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-helm-*-read', 'nx-repository-view-helm-*-read', 'Read privilege for all ''helm''-format repository views', 'repository-view', true, '{"format": "helm", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-maven2-*-*', 'nx-repository-view-maven2-*-*', 'All privileges for all ''maven2''-format repository views', 'repository-view', true, '{"format": "maven2", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-maven2-*-add', 'nx-repository-view-maven2-*-add', 'Add privilege for all ''maven2''-format repository views', 'repository-view', true, '{"format": "maven2", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-maven2-*-browse', 'nx-repository-view-maven2-*-browse', 'Browse privilege for all ''maven2''-format repository views', 'repository-view', true, '{"format": "maven2", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-maven2-*-delete', 'nx-repository-view-maven2-*-delete', 'Delete privilege for all ''maven2''-format repository views', 'repository-view', true, '{"format": "maven2", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-maven2-*-edit', 'nx-repository-view-maven2-*-edit', 'Edit privilege for all ''maven2''-format repository views', 'repository-view', true, '{"format": "maven2", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-maven2-*-read', 'nx-repository-view-maven2-*-read', 'Read privilege for all ''maven2''-format repository views', 'repository-view', true, '{"format": "maven2", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-npm-*-*', 'nx-repository-view-npm-*-*', 'All privileges for all ''npm''-format repository views', 'repository-view', true, '{"format": "npm", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-npm-*-add', 'nx-repository-view-npm-*-add', 'Add privilege for all ''npm''-format repository views', 'repository-view', true, '{"format": "npm", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-npm-*-browse', 'nx-repository-view-npm-*-browse', 'Browse privilege for all ''npm''-format repository views', 'repository-view', true, '{"format": "npm", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-npm-*-delete', 'nx-repository-view-npm-*-delete', 'Delete privilege for all ''npm''-format repository views', 'repository-view', true, '{"format": "npm", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-npm-*-edit', 'nx-repository-view-npm-*-edit', 'Edit privilege for all ''npm''-format repository views', 'repository-view', true, '{"format": "npm", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-npm-*-read', 'nx-repository-view-npm-*-read', 'Read privilege for all ''npm''-format repository views', 'repository-view', true, '{"format": "npm", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-pypi-*-*', 'nx-repository-view-pypi-*-*', 'All privileges for all ''pypi''-format repository views', 'repository-view', true, '{"format": "pypi", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-pypi-*-add', 'nx-repository-view-pypi-*-add', 'Add privilege for all ''pypi''-format repository views', 'repository-view', true, '{"format": "pypi", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-pypi-*-browse', 'nx-repository-view-pypi-*-browse', 'Browse privilege for all ''pypi''-format repository views', 'repository-view', true, '{"format": "pypi", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-pypi-*-delete', 'nx-repository-view-pypi-*-delete', 'Delete privilege for all ''pypi''-format repository views', 'repository-view', true, '{"format": "pypi", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-pypi-*-edit', 'nx-repository-view-pypi-*-edit', 'Edit privilege for all ''pypi''-format repository views', 'repository-view', true, '{"format": "pypi", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-pypi-*-read', 'nx-repository-view-pypi-*-read', 'Read privilege for all ''pypi''-format repository views', 'repository-view', true, '{"format": "pypi", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-raw-*-*', 'nx-repository-view-raw-*-*', 'All privileges for all ''raw''-format repository views', 'repository-view', true, '{"format": "raw", "actions": "*", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-raw-*-add', 'nx-repository-view-raw-*-add', 'Add privilege for all ''raw''-format repository views', 'repository-view', true, '{"format": "raw", "actions": "add", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-raw-*-browse', 'nx-repository-view-raw-*-browse', 'Browse privilege for all ''raw''-format repository views', 'repository-view', true, '{"format": "raw", "actions": "browse", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-raw-*-delete', 'nx-repository-view-raw-*-delete', 'Delete privilege for all ''raw''-format repository views', 'repository-view', true, '{"format": "raw", "actions": "delete", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-raw-*-edit', 'nx-repository-view-raw-*-edit', 'Edit privilege for all ''raw''-format repository views', 'repository-view', true, '{"format": "raw", "actions": "edit", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-repository-view-raw-*-read', 'nx-repository-view-raw-*-read', 'Read privilege for all ''raw''-format repository views', 'repository-view', true, '{"format": "raw", "actions": "read", "repository": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-roles-all', 'nx-roles-all', 'All permissions for Roles', 'application', true, '{"domain": "roles", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-roles-create', 'nx-roles-create', 'Create permission for Roles', 'application', true, '{"domain": "roles", "actions": "create,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-roles-delete', 'nx-roles-delete', 'Delete permission for Roles', 'application', true, '{"domain": "roles", "actions": "delete,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-roles-read', 'nx-roles-read', 'Read permission for Roles', 'application', true, '{"domain": "roles", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-roles-update', 'nx-roles-update', 'Update permission for Roles', 'application', true, '{"domain": "roles", "actions": "update,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-search-read', 'nx-search-read', 'Read permission for Search', 'application', true, '{"domain": "search", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-selectors-all', 'nx-selectors-all', 'All permissions for Content Selectors', 'application', true, '{"domain": "selectors", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-selectors-create', 'nx-selectors-create', 'Create permission for Content Selectors', 'application', true, '{"domain": "selectors", "actions": "create,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-selectors-delete', 'nx-selectors-delete', 'Delete permission for Content Selectors', 'application', true, '{"domain": "selectors", "actions": "delete,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-selectors-read', 'nx-selectors-read', 'Read permission for Content Selectors', 'application', true, '{"domain": "selectors", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-selectors-update', 'nx-selectors-update', 'Update permission for Content Selectors', 'application', true, '{"domain": "selectors", "actions": "update,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-settings-all', 'nx-settings-all', 'All permissions for Settings', 'application', true, '{"domain": "settings", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-settings-read', 'nx-settings-read', 'Read permission for Settings', 'application', true, '{"domain": "settings", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-settings-update', 'nx-settings-update', 'Update permission for Settings', 'application', true, '{"domain": "settings", "actions": "update,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-users-all', 'nx-users-all', 'All permissions for Users', 'application', true, '{"domain": "users", "actions": "*"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-users-create', 'nx-users-create', 'Create permission for Users', 'application', true, '{"domain": "users", "actions": "create,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-users-delete', 'nx-users-delete', 'Delete permission for Users', 'application', true, '{"domain": "users", "actions": "delete,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-users-read', 'nx-users-read', 'Read permission for Users', 'application', true, '{"domain": "users", "actions": "read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-users-update', 'nx-users-update', 'Update permission for Users', 'application', true, '{"domain": "users", "actions": "update,read"}');
INSERT INTO security_privilege (privilege_id, name, description, type, read_only, properties_json) VALUES ('nx-userschangepw', 'nx-userschangepw', 'Change password permission', 'application', true, '{"domain": "userschangepw", "actions": "create,read"}');
INSERT INTO security_realm (id, realm_id, type, name, enabled, priority, attributes_json) VALUES (1, 'local', 'LOCAL', 'Local', true, 0, '{"source": "Local", "nexusRealm": "NexusAuthenticatingRealm"}');
INSERT INTO security_realm (id, realm_id, type, name, enabled, priority, attributes_json) VALUES (2, 'ldap', 'LDAP', 'LDAP', false, 10, '{"source": "LDAP", "nexusRealm": "LdapRealm"}');
INSERT INTO security_realm (id, realm_id, type, name, enabled, priority, attributes_json) VALUES (3, 'oidc', 'OIDC', 'OIDC', false, 20, '{"source": "OIDC", "nexusRealm": "OidcRealm"}');
INSERT INTO security_realm_config (id, realms_json) VALUES (1, '{"realms": ["local"]}');
INSERT INTO security_role (role_id, source, name, description, read_only, attributes_json) VALUES ('nx-admin', 'Local', 'nx-admin', 'Administrator role with all Nexus privileges', true, '{}');
INSERT INTO security_role (role_id, source, name, description, read_only, attributes_json) VALUES ('nx-anonymous', 'Local', 'nx-anonymous', 'Anonymous Role', true, '{"source": "nexus-builtin"}');
INSERT INTO security_user (id, source, user_id, first_name, last_name, email, password_hash, status, external_id, attributes_json) VALUES (1, 'Local', 'anonymous', 'Anonymous', 'User', 'anonymous@example.invalid', NULL, 'ACTIVE', NULL, '{"source": "nexus-builtin"}');
INSERT INTO security_role_privilege (role_id, privilege_id) VALUES ('nx-admin', 'nx-all');
INSERT INTO security_role_privilege (role_id, privilege_id) VALUES ('nx-anonymous', 'nx-healthcheck-read');
INSERT INTO security_role_privilege (role_id, privilege_id) VALUES ('nx-anonymous', 'nx-repository-view-*-*-browse');
INSERT INTO security_role_privilege (role_id, privilege_id) VALUES ('nx-anonymous', 'nx-repository-view-*-*-read');
INSERT INTO security_role_privilege (role_id, privilege_id) VALUES ('nx-anonymous', 'nx-search-read');
INSERT INTO security_user_role (user_id, role_id) VALUES (1, 'nx-anonymous');
INSERT INTO security_anonymous_config (id, enabled, user_source, user_id, realm_name) VALUES (1, false, 'Local', 'anonymous', 'NexusAuthorizingRealm');
INSERT INTO ui_settings (id, default_language) VALUES (1, 'en');

SELECT setval(pg_get_serial_sequence('security_realm', 'id'), (SELECT MAX(id) FROM security_realm), true);
SELECT setval(pg_get_serial_sequence('security_user', 'id'), (SELECT MAX(id) FROM security_user), true);
