CREATE TABLE swift_release (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  component_id BIGINT NOT NULL REFERENCES component(id) ON DELETE CASCADE,
  scope_lc VARCHAR(64) NOT NULL,
  scope_display VARCHAR(64) NOT NULL,
  name_lc VARCHAR(128) NOT NULL,
  name_display VARCHAR(128) NOT NULL,
  version VARCHAR(128) NOT NULL,
  published_at TIMESTAMPTZ(3) NOT NULL,
  metadata_json JSONB NOT NULL,
  archive_sha256 CHAR(64) NOT NULL,
  archive_asset_id BIGINT NOT NULL REFERENCES asset(id) ON DELETE RESTRICT,
  signature_format VARCHAR(64),
  source_signature_asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  metadata_signature_asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  source_kind VARCHAR(16) NOT NULL,
  revision BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'READY',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_swift_release_component UNIQUE (component_id),
  CONSTRAINT uk_swift_release_coordinate UNIQUE (repository_id, scope_lc, name_lc, version)
);
CREATE INDEX idx_swift_release_package
  ON swift_release(repository_id, scope_lc, name_lc, status, version);
CREATE INDEX idx_swift_release_revision ON swift_release(repository_id, revision);

CREATE TABLE swift_manifest (
  release_id BIGINT NOT NULL REFERENCES swift_release(id) ON DELETE CASCADE,
  filename VARCHAR(255) NOT NULL,
  tools_version VARCHAR(32) NOT NULL DEFAULT '',
  asset_id BIGINT NOT NULL REFERENCES asset(id) ON DELETE RESTRICT,
  sha256 CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (release_id, tools_version),
  CONSTRAINT uk_swift_manifest_filename UNIQUE (release_id, filename),
  CONSTRAINT uk_swift_manifest_asset UNIQUE (asset_id)
);

CREATE TABLE swift_repository_url (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_id BIGINT NOT NULL REFERENCES swift_release(id) ON DELETE CASCADE,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  scope_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(128) NOT NULL,
  normalized_url VARCHAR(1024) NOT NULL,
  normalized_url_hash BYTEA NOT NULL,
  display_url VARCHAR(1024) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_swift_repository_url UNIQUE (release_id, normalized_url_hash)
);
CREATE INDEX idx_swift_url_lookup ON swift_repository_url(repository_id, normalized_url_hash);

CREATE TABLE swift_proxy_source (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  scope_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(128) NOT NULL,
  version VARCHAR(128) NOT NULL,
  upstream_repository_url VARCHAR(1024) NOT NULL,
  upstream_tag VARCHAR(255) NOT NULL,
  commit_sha VARCHAR(64) NOT NULL,
  generation_profile VARCHAR(128) NOT NULL,
  archive_sha256 CHAR(64),
  cache_state VARCHAR(16) NOT NULL,
  release_id BIGINT REFERENCES swift_release(id) ON DELETE SET NULL,
  verified_at TIMESTAMPTZ(3),
  revision BIGINT NOT NULL,
  observed_count BIGINT NOT NULL DEFAULT 1,
  last_checked_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, scope_lc, name_lc, version)
);
CREATE INDEX idx_swift_proxy_commit ON swift_proxy_source(repository_id, commit_sha);
CREATE INDEX idx_swift_proxy_state ON swift_proxy_source(repository_id, cache_state, last_checked_at);

CREATE TABLE swift_group_source_binding (
  group_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  scope_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(128) NOT NULL,
  version VARCHAR(128) NOT NULL,
  member_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  member_release_id BIGINT NOT NULL REFERENCES swift_release(id) ON DELETE CASCADE,
  member_revision BIGINT NOT NULL,
  group_config_revision BIGINT NOT NULL,
  observed_count BIGINT NOT NULL DEFAULT 1,
  bound_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (group_repository_id, scope_lc, name_lc, version)
);
CREATE INDEX idx_swift_group_member
  ON swift_group_source_binding(member_repository_id, member_revision);

CREATE TABLE swift_coordinate_lease (
  lease_key VARCHAR(512) PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  attempt_count BIGINT NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_swift_lease_expiry ON swift_coordinate_lease(expires_at);

CREATE TABLE swift_release_tombstone (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  scope_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(128) NOT NULL,
  version VARCHAR(128) NOT NULL,
  reason VARCHAR(255),
  revision BIGINT NOT NULL,
  deleted_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, scope_lc, name_lc, version)
);
CREATE INDEX idx_swift_tombstone_revision ON swift_release_tombstone(repository_id, revision);

CREATE TABLE swift_proxy_negative_cache (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  cache_key VARCHAR(512) NOT NULL,
  cache_key_hash BYTEA NOT NULL,
  status_code INTEGER NOT NULL,
  retry_after TIMESTAMPTZ(3),
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, cache_key_hash)
);
CREATE INDEX idx_swift_negative_expiry ON swift_proxy_negative_cache(expires_at);
