CREATE TABLE ansible_collection_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  component_id BIGINT NOT NULL REFERENCES component(id) ON DELETE CASCADE,
  artifact_asset_id BIGINT NOT NULL REFERENCES asset(id) ON DELETE RESTRICT,
  namespace_lc VARCHAR(64) NOT NULL,
  namespace_display VARCHAR(64) NOT NULL,
  name_lc VARCHAR(64) NOT NULL,
  name_display VARCHAR(64) NOT NULL,
  version_original VARCHAR(128) NOT NULL,
  version_normalized VARCHAR(128) NOT NULL,
  artifact_filename VARCHAR(255) NOT NULL,
  artifact_sha256 CHAR(64) NOT NULL,
  artifact_size BIGINT NOT NULL,
  metadata_json JSONB NOT NULL,
  dependencies_json JSONB NOT NULL,
  requires_ansible VARCHAR(255),
  source_kind VARCHAR(16) NOT NULL,
  revision BIGINT NOT NULL,
  state VARCHAR(16) NOT NULL DEFAULT 'READY',
  published_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_ansible_version_component UNIQUE (component_id),
  CONSTRAINT uk_ansible_version_asset UNIQUE (artifact_asset_id),
  CONSTRAINT uk_ansible_version_coordinate
    UNIQUE (repository_id, namespace_lc, name_lc, version_normalized),
  CONSTRAINT uk_ansible_version_filename UNIQUE (repository_id, artifact_filename)
);
CREATE INDEX idx_ansible_collection
  ON ansible_collection_version(repository_id, namespace_lc, name_lc, state, revision);
CREATE INDEX idx_ansible_version_revision
  ON ansible_collection_version(repository_id, revision);

CREATE TABLE ansible_collection_signature (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_version_id BIGINT NOT NULL
    REFERENCES ansible_collection_version(id) ON DELETE CASCADE,
  signature_asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  sha256 CHAR(64) NOT NULL,
  key_fingerprint VARCHAR(128),
  source_kind VARCHAR(16) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_ansible_signature UNIQUE (collection_version_id, sha256)
);

CREATE TABLE ansible_import_task (
  task_uuid CHAR(36) PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  requester VARCHAR(255),
  state VARCHAR(16) NOT NULL,
  messages_json JSONB NOT NULL,
  error_code VARCHAR(128),
  error_detail VARCHAR(2048),
  namespace_lc VARCHAR(64),
  name_lc VARCHAR(64),
  version_normalized VARCHAR(128),
  artifact_filename VARCHAR(255),
  expected_sha256 CHAR(64),
  actual_sha256 CHAR(64),
  staging_asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  lease_owner VARCHAR(128),
  lease_expires_at TIMESTAMPTZ(3),
  fencing_token BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(3) NOT NULL,
  started_at TIMESTAMPTZ(3),
  finished_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_ansible_task_claim
  ON ansible_import_task(state, lease_expires_at, created_at);
CREATE INDEX idx_ansible_task_repository
  ON ansible_import_task(repository_id, created_at);
CREATE INDEX idx_ansible_task_terminal
  ON ansible_import_task(state, finished_at);

CREATE TABLE ansible_proxy_version_state (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  namespace_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(64) NOT NULL,
  version_normalized VARCHAR(128) NOT NULL,
  artifact_filename VARCHAR(255),
  upstream_href VARCHAR(2048),
  upstream_download_url VARCHAR(2048),
  artifact_sha256 CHAR(64),
  metadata_etag VARCHAR(512),
  metadata_last_modified VARCHAR(255),
  cache_until TIMESTAMPTZ(3),
  verified_at TIMESTAMPTZ(3),
  negative_status INTEGER,
  negative_expires_at TIMESTAMPTZ(3),
  protocol_metadata_json JSONB NOT NULL,
  revision BIGINT NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, namespace_lc, name_lc, version_normalized)
);
CREATE INDEX idx_ansible_proxy_expiry
  ON ansible_proxy_version_state(repository_id, cache_until);
CREATE INDEX idx_ansible_proxy_artifact
  ON ansible_proxy_version_state(repository_id, artifact_filename);
CREATE INDEX idx_ansible_proxy_negative
  ON ansible_proxy_version_state(negative_expires_at);
CREATE INDEX idx_ansible_proxy_updated
  ON ansible_proxy_version_state(updated_at);

CREATE TABLE ansible_proxy_inventory (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  namespace_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(64) NOT NULL,
  cache_until TIMESTAMPTZ(3) NOT NULL,
  checked_at TIMESTAMPTZ(3) NOT NULL,
  revision BIGINT NOT NULL,
  version_count INTEGER NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, namespace_lc, name_lc)
);
CREATE INDEX idx_ansible_inventory_expiry
  ON ansible_proxy_inventory(cache_until, updated_at);

CREATE TABLE ansible_proxy_inventory_version (
  repository_id BIGINT NOT NULL,
  namespace_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(64) NOT NULL,
  version_normalized VARCHAR(128) NOT NULL,
  PRIMARY KEY (repository_id, namespace_lc, name_lc, version_normalized),
  CONSTRAINT fk_ansible_inventory_version
    FOREIGN KEY (repository_id, namespace_lc, name_lc)
    REFERENCES ansible_proxy_inventory(repository_id, namespace_lc, name_lc)
    ON DELETE CASCADE
);

CREATE TABLE ansible_group_binding (
  group_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  namespace_lc VARCHAR(64) NOT NULL,
  name_lc VARCHAR(64) NOT NULL,
  version_normalized VARCHAR(128) NOT NULL,
  member_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  member_version_id BIGINT NULL REFERENCES ansible_collection_version(id) ON DELETE CASCADE,
  artifact_filename VARCHAR(255) NOT NULL,
  member_revision BIGINT NOT NULL,
  group_config_revision BIGINT NOT NULL,
  artifact_sha256 CHAR(64) NOT NULL,
  observed_count BIGINT NOT NULL DEFAULT 1,
  bound_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (group_repository_id, namespace_lc, name_lc, version_normalized)
);
CREATE INDEX idx_ansible_group_member
  ON ansible_group_binding(member_repository_id, member_revision);
CREATE INDEX idx_ansible_group_artifact
  ON ansible_group_binding(group_repository_id, artifact_filename);

CREATE TABLE ansible_registry_lease (
  lease_key VARCHAR(512) PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  attempt_count BIGINT NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_ansible_lease_expiry ON ansible_registry_lease(expires_at);
