CREATE TABLE asset_public_identifier (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  opaque_id VARCHAR(32) NOT NULL,
  asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  native_asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  identifier_type VARCHAR(32) NOT NULL,
  source_instance VARCHAR(1024),
  migration_job_id BIGINT,
  created_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_asset_public_identifier UNIQUE (repository_id, opaque_id),
  CONSTRAINT uk_asset_public_identifier_native UNIQUE (native_asset_id),
  CONSTRAINT ck_asset_public_identifier_type
      CHECK (identifier_type IN ('KKREPO_NATIVE', 'NEXUS_ALIAS'))
);

CREATE INDEX idx_asset_public_identifier_asset
  ON asset_public_identifier (asset_id, identifier_type);

INSERT INTO asset_public_identifier
  (repository_id, opaque_id, asset_id, native_asset_id, identifier_type)
SELECT repository_id, LPAD(LOWER(TO_HEX(id)), 32, '0'), id, id, 'KKREPO_NATIVE'
FROM asset;
