CREATE INDEX idx_asset_repository_id
  ON asset(repository_id, id);

CREATE TABLE artifact_change_event (
  id BIGSERIAL PRIMARY KEY,
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  asset_id BIGINT NOT NULL CHECK (asset_id >= 0),
  previous_asset_blob_id BIGINT CHECK (previous_asset_blob_id >= 0),
  asset_blob_id BIGINT NOT NULL CHECK (asset_blob_id >= 0),
  change_kind VARCHAR(32) NOT NULL,
  occurred_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_artifact_change_repository
  ON artifact_change_event(repository_id, id);
CREATE INDEX idx_artifact_change_asset
  ON artifact_change_event(asset_id, id);

CREATE TABLE blob_reference (
  owner_type VARCHAR(64) NOT NULL,
  owner_id BIGINT NOT NULL CHECK (owner_id >= 0),
  blob_id BIGINT NOT NULL REFERENCES asset_blob(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (owner_type, owner_id, blob_id)
);
CREATE INDEX idx_blob_reference_blob ON blob_reference(blob_id);

CREATE INDEX idx_docker_reference_policy_lookup
  ON docker_manifest_reference(repository_id, digest_hash, image_name, manifest_id);

CREATE TABLE security_scan_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  catalog_engine VARCHAR(64) NOT NULL,
  matcher_engine VARCHAR(64) NOT NULL,
  scanner_types_json JSONB NOT NULL,
  target_rules_json JSONB NOT NULL,
  max_input_bytes BIGINT NOT NULL,
  max_archive_entries INTEGER NOT NULL,
  max_uncompressed_bytes BIGINT NOT NULL,
  max_single_file_bytes BIGINT NOT NULL,
  max_nested_depth INTEGER NOT NULL,
  timeout_seconds INTEGER NOT NULL,
  oci_platform_policy VARCHAR(32) NOT NULL,
  required_platforms_json JSONB NOT NULL,
  configuration_digest CHAR(64) NOT NULL,
  revision BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT uk_security_scan_profile_name UNIQUE (name),
  CONSTRAINT uk_security_scan_profile_digest UNIQUE (configuration_digest)
);

CREATE TABLE security_scan_policy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  block_severity VARCHAR(16) NOT NULL,
  only_fixable BOOLEAN NOT NULL DEFAULT FALSE,
  block_unknown_severity BOOLEAN NOT NULL DEFAULT FALSE,
  require_complete_inventory BOOLEAN NOT NULL DEFAULT FALSE,
  max_result_age_seconds BIGINT,
  required_platforms_json JSONB NOT NULL,
  revision BIGINT NOT NULL,
  created_by VARCHAR(255),
  created_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT uk_security_scan_policy_name_revision UNIQUE (name, revision)
);
CREATE INDEX idx_security_scan_policy_active
  ON security_scan_policy(enabled, name, revision);

CREATE TABLE repository_security_scan_config (
  repository_id BIGINT PRIMARY KEY REFERENCES repository(id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  profile_id BIGINT NOT NULL REFERENCES security_scan_profile(id) ON DELETE RESTRICT,
  scan_hosted_content BOOLEAN NOT NULL DEFAULT TRUE,
  scan_proxy_content BOOLEAN NOT NULL DEFAULT TRUE,
  enforcement_mode VARCHAR(16) NOT NULL DEFAULT 'AUDIT',
  pending_action VARCHAR(16) NOT NULL DEFAULT 'ALLOW',
  failure_action VARCHAR(16) NOT NULL DEFAULT 'ALLOW',
  partial_action VARCHAR(16) NOT NULL DEFAULT 'ALLOW',
  max_result_age_seconds BIGINT,
  policy_id BIGINT REFERENCES security_scan_policy(id) ON DELETE SET NULL,
  config_revision BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_repository_security_scan_enabled
  ON repository_security_scan_config(enabled, repository_id);
CREATE INDEX idx_repository_security_scan_profile
  ON repository_security_scan_config(profile_id);

CREATE TABLE security_scan_candidate (
  asset_id BIGINT PRIMARY KEY REFERENCES asset(id) ON DELETE CASCADE,
  asset_blob_id BIGINT REFERENCES asset_blob(id) ON DELETE SET NULL,
  content_generation BIGINT NOT NULL,
  enqueued_generation BIGINT NOT NULL DEFAULT 0,
  pending BOOLEAN GENERATED ALWAYS AS (content_generation > enqueued_generation) STORED,
  changed_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_security_scan_candidate_queue
  ON security_scan_candidate(pending, changed_at, asset_id);

CREATE TABLE security_scanner_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adapter_name VARCHAR(128) NOT NULL,
  adapter_api_version VARCHAR(32) NOT NULL,
  engine_name VARCHAR(128) NOT NULL,
  engine_version VARCHAR(128) NOT NULL,
  vulnerability_database_revision VARCHAR(255),
  vulnerability_database_updated_at TIMESTAMPTZ(3),
  capability_digest CHAR(64) NOT NULL,
  snapshot_fingerprint CHAR(64) NOT NULL,
  observed_at TIMESTAMPTZ(3) NOT NULL,
  ready BOOLEAN NOT NULL,
  details_json JSONB NOT NULL,
  CONSTRAINT uk_security_scanner_snapshot UNIQUE (snapshot_fingerprint)
);
CREATE INDEX idx_security_scanner_snapshot_observed
  ON security_scanner_snapshot(observed_at, id);
CREATE INDEX idx_security_scanner_snapshot_ready
  ON security_scanner_snapshot(ready, observed_at);

CREATE TABLE security_scan_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  subject_kind VARCHAR(32) NOT NULL,
  subject_key VARCHAR(1024) NOT NULL,
  subject_key_hash BYTEA NOT NULL,
  content_generation BIGINT NOT NULL,
  profile_id BIGINT NOT NULL REFERENCES security_scan_profile(id) ON DELETE RESTRICT,
  profile_revision BIGINT NOT NULL,
  requested_scanner_snapshot_id BIGINT
    REFERENCES security_scanner_snapshot(id) ON DELETE SET NULL,
  stage VARCHAR(32) NOT NULL,
  request_reason VARCHAR(48) NOT NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL,
  next_attempt_at TIMESTAMPTZ(3) NOT NULL,
  claimed_by VARCHAR(128),
  lease_token CHAR(36),
  lease_until TIMESTAMPTZ(3),
  last_heartbeat_at TIMESTAMPTZ(3),
  last_error_code VARCHAR(128),
  last_error_summary VARCHAR(2048),
  requested_by VARCHAR(255),
  request_uuid CHAR(36),
  idempotency_key_hash BYTEA,
  requested_at TIMESTAMPTZ(3) NOT NULL,
  started_at TIMESTAMPTZ(3),
  finished_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL,
  dedupe_key BYTEA NOT NULL,
  CONSTRAINT uk_security_scan_task_dedupe UNIQUE (dedupe_key),
  CONSTRAINT uk_security_scan_task_idempotency UNIQUE (repository_id, idempotency_key_hash)
);
CREATE INDEX idx_security_scan_task_claim
  ON security_scan_task(status, next_attempt_at, lease_until, priority, requested_at, id);
CREATE INDEX idx_security_scan_task_requested_snapshot
  ON security_scan_task(requested_scanner_snapshot_id);
CREATE INDEX idx_security_scan_task_asset
  ON security_scan_task(asset_id, created_at, id);
CREATE INDEX idx_security_scan_task_repository
  ON security_scan_task(repository_id, created_at, id);
CREATE INDEX idx_security_scan_task_repository_status
  ON security_scan_task(repository_id, status, id);
CREATE INDEX idx_security_scan_task_terminal
  ON security_scan_task(status, finished_at);
CREATE INDEX idx_security_scan_task_pending_age
  ON security_scan_task(status, created_at, id);

CREATE TABLE security_sbom (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_kind VARCHAR(32) NOT NULL,
  subject_identity VARCHAR(1024) NOT NULL,
  subject_identity_hash BYTEA NOT NULL,
  catalog_engine VARCHAR(128) NOT NULL,
  catalog_engine_version VARCHAR(128) NOT NULL,
  catalog_configuration_digest CHAR(64) NOT NULL,
  catalog_fingerprint CHAR(64) NOT NULL,
  document_blob_id BIGINT NOT NULL REFERENCES asset_blob(id) ON DELETE RESTRICT,
  document_sha256 CHAR(64) NOT NULL,
  spec_name VARCHAR(64) NOT NULL,
  spec_version VARCHAR(32) NOT NULL,
  component_count INTEGER NOT NULL,
  dependency_count INTEGER NOT NULL,
  inventory_complete BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL,
  last_accessed_at TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT uk_security_sbom_catalog_fingerprint UNIQUE (catalog_fingerprint)
);
CREATE INDEX idx_security_sbom_subject
  ON security_sbom(subject_identity_hash, created_at, id);
CREATE INDEX idx_security_sbom_retention
  ON security_sbom(last_accessed_at, id);
CREATE INDEX idx_security_sbom_document_blob
  ON security_sbom(document_blob_id);

CREATE TABLE security_sbom_component (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sbom_id BIGINT NOT NULL REFERENCES security_sbom(id) ON DELETE CASCADE,
  component_ref VARCHAR(1024) NOT NULL,
  component_ref_hash BYTEA NOT NULL,
  package_url VARCHAR(2048),
  package_url_hash BYTEA,
  component_type VARCHAR(64),
  namespace VARCHAR(512),
  name VARCHAR(512) NOT NULL,
  version VARCHAR(512),
  directness VARCHAR(32),
  locations_json JSONB NOT NULL,
  licenses_json JSONB NOT NULL,
  properties_json JSONB NOT NULL,
  CONSTRAINT uk_security_sbom_component_ref UNIQUE (sbom_id, component_ref_hash)
);
CREATE INDEX idx_security_sbom_component_purl
  ON security_sbom_component(package_url_hash);
CREATE INDEX idx_security_sbom_component_name
  ON security_sbom_component(name, version);

CREATE TABLE security_scan_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES security_scan_task(id) ON DELETE SET NULL,
  sbom_id BIGINT NOT NULL REFERENCES security_sbom(id) ON DELETE RESTRICT,
  scanner_snapshot_id BIGINT NOT NULL
    REFERENCES security_scanner_snapshot(id) ON DELETE RESTRICT,
  match_configuration_digest CHAR(64) NOT NULL,
  match_fingerprint CHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL,
  scan_completeness VARCHAR(24) NOT NULL,
  raw_report_blob_id BIGINT NOT NULL REFERENCES asset_blob(id) ON DELETE RESTRICT,
  raw_report_sha256 CHAR(64) NOT NULL,
  finding_count INTEGER NOT NULL,
  fixable_finding_count INTEGER NOT NULL,
  critical_count INTEGER NOT NULL,
  high_count INTEGER NOT NULL,
  medium_count INTEGER NOT NULL,
  low_count INTEGER NOT NULL,
  unknown_count INTEGER NOT NULL,
  max_severity VARCHAR(16) NOT NULL,
  scanned_platforms_json JSONB NOT NULL,
  missing_platforms_json JSONB NOT NULL,
  started_at TIMESTAMPTZ(3) NOT NULL,
  completed_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL,
  last_accessed_at TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT uk_security_scan_run_match_fingerprint UNIQUE (match_fingerprint)
);
CREATE INDEX idx_security_scan_run_sbom
  ON security_scan_run(sbom_id, created_at, id);
CREATE INDEX idx_security_scan_run_task ON security_scan_run(task_id);
CREATE INDEX idx_security_scan_run_snapshot ON security_scan_run(scanner_snapshot_id);
CREATE INDEX idx_security_scan_run_report_blob ON security_scan_run(raw_report_blob_id);
CREATE INDEX idx_security_scan_run_status ON security_scan_run(status, completed_at);
CREATE INDEX idx_security_scan_run_retention
  ON security_scan_run(last_accessed_at, completed_at, id);

CREATE TABLE security_scan_run_subject (
  scan_run_id BIGINT NOT NULL REFERENCES security_scan_run(id) ON DELETE CASCADE,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  asset_id BIGINT NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
  profile_id BIGINT NOT NULL REFERENCES security_scan_profile(id) ON DELETE RESTRICT,
  content_generation BIGINT NOT NULL,
  associated_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (scan_run_id, repository_id, asset_id, profile_id, content_generation)
);
CREATE INDEX idx_security_scan_run_subject_repository
  ON security_scan_run_subject(repository_id, scan_run_id);
CREATE INDEX idx_security_scan_run_subject_asset
  ON security_scan_run_subject(asset_id, profile_id, associated_at);
CREATE INDEX idx_security_scan_run_subject_retention
  ON security_scan_run_subject(associated_at, scan_run_id);

CREATE TABLE security_scan_finding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scan_run_id BIGINT NOT NULL REFERENCES security_scan_run(id) ON DELETE CASCADE,
  finding_key VARCHAR(2048) NOT NULL,
  finding_key_hash BYTEA NOT NULL,
  advisory_id VARCHAR(255) NOT NULL,
  aliases_json JSONB NOT NULL,
  data_source VARCHAR(2048),
  package_url VARCHAR(2048),
  package_name VARCHAR(512) NOT NULL,
  installed_version VARCHAR(512),
  fixed_versions_json JSONB NOT NULL,
  severity VARCHAR(16) NOT NULL,
  severity_source VARCHAR(128),
  cvss_vector VARCHAR(255),
  cvss_score NUMERIC(4,1),
  title VARCHAR(1024),
  description TEXT,
  primary_url VARCHAR(2048),
  locations_json JSONB NOT NULL,
  source_status VARCHAR(64),
  created_at TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT uk_security_scan_finding_key UNIQUE (scan_run_id, finding_key_hash)
);
CREATE INDEX idx_security_scan_finding_advisory
  ON security_scan_finding(advisory_id, severity);
CREATE INDEX idx_security_scan_finding_package
  ON security_scan_finding(package_name, installed_version);
CREATE INDEX idx_security_scan_finding_severity
  ON security_scan_finding(severity, scan_run_id, id);

CREATE TABLE asset_security_state (
  asset_id BIGINT NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
  profile_id BIGINT NOT NULL REFERENCES security_scan_profile(id) ON DELETE RESTRICT,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  content_generation BIGINT NOT NULL,
  subject_identity_hash BYTEA NOT NULL,
  latest_scan_run_id BIGINT REFERENCES security_scan_run(id) ON DELETE SET NULL,
  scan_state VARCHAR(24) NOT NULL,
  scan_completeness VARCHAR(24) NOT NULL,
  inventory_complete BOOLEAN NOT NULL,
  max_severity VARCHAR(16) NOT NULL,
  finding_counts_json JSONB NOT NULL,
  policy_id BIGINT REFERENCES security_scan_policy(id) ON DELETE SET NULL,
  policy_revision BIGINT,
  policy_decision VARCHAR(32) NOT NULL,
  policy_reason_code VARCHAR(128) NOT NULL,
  stale_at TIMESTAMPTZ(3),
  last_evaluated_at TIMESTAMPTZ(3) NOT NULL,
  version BIGINT NOT NULL,
  PRIMARY KEY (asset_id, profile_id)
);
CREATE INDEX idx_asset_security_state_decision
  ON asset_security_state(policy_decision, scan_state, asset_id);
CREATE INDEX idx_asset_security_state_stale
  ON asset_security_state(stale_at, scan_state);
CREATE INDEX idx_asset_security_state_run
  ON asset_security_state(latest_scan_run_id);
CREATE INDEX idx_asset_security_state_scan
  ON asset_security_state(scan_state, asset_id);
CREATE INDEX idx_asset_security_state_repository_summary
  ON asset_security_state(repository_id, scan_state, policy_decision);

CREATE TABLE asset_security_policy_state (
  asset_id BIGINT NOT NULL REFERENCES asset(id) ON DELETE CASCADE,
  profile_id BIGINT NOT NULL REFERENCES security_scan_profile(id) ON DELETE RESTRICT,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  content_generation BIGINT NOT NULL,
  latest_scan_run_id BIGINT REFERENCES security_scan_run(id) ON DELETE SET NULL,
  policy_id BIGINT REFERENCES security_scan_policy(id) ON DELETE SET NULL,
  policy_revision BIGINT,
  config_revision BIGINT NOT NULL,
  waiver_revision BIGINT NOT NULL DEFAULT 0,
  policy_decision VARCHAR(32) NOT NULL,
  policy_reason_code VARCHAR(128) NOT NULL,
  waived_findings INTEGER NOT NULL DEFAULT 0,
  stale_at TIMESTAMPTZ(3),
  next_waiver_expiry TIMESTAMPTZ(3),
  last_evaluated_at TIMESTAMPTZ(3) NOT NULL,
  version BIGINT NOT NULL,
  PRIMARY KEY (asset_id, profile_id, repository_id)
);
CREATE INDEX idx_asset_security_policy_context
  ON asset_security_policy_state(
    repository_id, profile_id, config_revision, waiver_revision, asset_id);
CREATE INDEX idx_asset_security_policy_summary
  ON asset_security_policy_state(
    repository_id, policy_decision, asset_id, profile_id);
CREATE INDEX idx_asset_security_policy_expiry
  ON asset_security_policy_state(next_waiver_expiry, repository_id);
CREATE INDEX idx_asset_security_policy_run
  ON asset_security_policy_state(latest_scan_run_id);

CREATE TABLE security_scan_waiver_revision (
  singleton_id SMALLINT PRIMARY KEY CHECK (singleton_id = 1),
  current_revision BIGINT NOT NULL,
  global_invalidation_revision BIGINT NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);

INSERT INTO security_scan_waiver_revision
  (singleton_id, current_revision, global_invalidation_revision, updated_at)
VALUES (1, 0, 0, CURRENT_TIMESTAMP);

CREATE TABLE security_scan_waiver (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type VARCHAR(24) NOT NULL,
  repository_id BIGINT REFERENCES repository(id) ON DELETE CASCADE,
  asset_id BIGINT REFERENCES asset(id) ON DELETE CASCADE,
  finding_id BIGINT REFERENCES security_scan_finding(id) ON DELETE CASCADE,
  advisory_selector VARCHAR(255),
  package_selector VARCHAR(2048),
  selector_json JSONB NOT NULL,
  reason VARCHAR(2048) NOT NULL,
  policy_id BIGINT REFERENCES security_scan_policy(id) ON DELETE SET NULL,
  policy_revision BIGINT,
  created_by VARCHAR(255) NOT NULL,
  approved_by VARCHAR(255),
  expires_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_security_scan_waiver_active
  ON security_scan_waiver(repository_id, asset_id, id, expires_at);
CREATE INDEX idx_security_scan_waiver_finding
  ON security_scan_waiver(finding_id);
CREATE INDEX idx_security_scan_waiver_advisory
  ON security_scan_waiver(advisory_selector);
CREATE INDEX idx_security_scan_waiver_package
  ON security_scan_waiver(package_selector);

CREATE TABLE security_scan_backfill_job (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  status VARCHAR(24) NOT NULL,
  cursor_asset_id BIGINT NOT NULL DEFAULT 0,
  scanned_assets BIGINT NOT NULL DEFAULT 0,
  marked_assets BIGINT NOT NULL DEFAULT 0,
  attempts INTEGER NOT NULL DEFAULT 0,
  claimed_by VARCHAR(128),
  lease_token CHAR(36),
  lease_until TIMESTAMPTZ(3),
  next_attempt_at TIMESTAMPTZ(3),
  last_error_summary VARCHAR(2048),
  created_by VARCHAR(255),
  created_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL,
  completed_at TIMESTAMPTZ(3)
);
CREATE INDEX idx_security_scan_backfill_claim_pending
  ON security_scan_backfill_job(status, next_attempt_at, created_at, id);
CREATE INDEX idx_security_scan_backfill_claim_running
  ON security_scan_backfill_job(status, lease_until, created_at, id);
CREATE INDEX idx_security_scan_backfill_repository
  ON security_scan_backfill_job(repository_id, created_at, id);
CREATE INDEX idx_security_scan_backfill_retention
  ON security_scan_backfill_job(status, completed_at, id);

INSERT INTO security_scan_profile
  (id, name, enabled, catalog_engine, matcher_engine, scanner_types_json,
   target_rules_json, max_input_bytes, max_archive_entries, max_uncompressed_bytes,
   max_single_file_bytes, max_nested_depth, timeout_seconds, oci_platform_policy,
   required_platforms_json, configuration_digest, revision, created_at, updated_at)
VALUES
  (1, 'syft-grype-v1', TRUE, 'syft', 'grype', '["vuln"]'::jsonb, '{}'::jsonb,
   1073741824, 100000, 10737418240, 1073741824, 3, 900, 'REQUIRED_SET',
   '["linux/amd64"]'::jsonb,
   'a939b553200d01acf4f7a5f7ff122ff045714827dc7266b1e8f05cba7a2c32ca',
   1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO security_scan_policy
  (id, name, enabled, block_severity, only_fixable, block_unknown_severity,
   require_complete_inventory, max_result_age_seconds, required_platforms_json,
   revision, created_by, created_at, updated_at)
VALUES
  (1, 'default-audit', TRUE, 'CRITICAL', FALSE, FALSE, FALSE, 604800,
   '["linux/amd64"]'::jsonb, 1, 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

SELECT setval(
  pg_get_serial_sequence('security_scan_profile', 'id'),
  GREATEST((SELECT MAX(id) FROM security_scan_profile), 1),
  TRUE);
SELECT setval(
  pg_get_serial_sequence('security_scan_policy', 'id'),
  GREATEST((SELECT MAX(id) FROM security_scan_policy), 1),
  TRUE);

INSERT INTO maintenance_cursor (task_name, last_seen_id)
VALUES ('artifact_change:security_scan', 0);
