ALTER TABLE cleanup_policy
  ADD COLUMN revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
  ADD COLUMN state VARCHAR(32) NOT NULL DEFAULT 'PAUSED',
  ADD COLUMN scan_limit_per_repository INTEGER NOT NULL DEFAULT 1000
    CHECK (scan_limit_per_repository > 0),
  ADD COLUMN delete_limit_per_repository INTEGER NOT NULL DEFAULT 100
    CHECK (delete_limit_per_repository > 0);

DROP INDEX uk_cleanup_policy_name;
CREATE UNIQUE INDEX uk_cleanup_policy_active_name
  ON cleanup_policy (name) WHERE state <> 'DELETED';

CREATE TABLE cleanup_policy_schedule (
  policy_id BIGINT NOT NULL CHECK (policy_id >= 0),
  cron_expression VARCHAR(120) NOT NULL,
  time_zone VARCHAR(64) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_policy_schedule PRIMARY KEY (policy_id),
  CONSTRAINT fk_cleanup_policy_schedule_policy
    FOREIGN KEY (policy_id) REFERENCES cleanup_policy (id) ON DELETE CASCADE
);

CREATE TABLE cleanup_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  policy_id BIGINT NOT NULL CHECK (policy_id >= 0),
  policy_revision BIGINT NOT NULL CHECK (policy_revision > 0),
  mode VARCHAR(16) NOT NULL,
  trigger_kind VARCHAR(16) NOT NULL,
  state VARCHAR(32) NOT NULL,
  requested_by VARCHAR(255) NOT NULL,
  scheduled_for TIMESTAMPTZ(3),
  scan_limit_per_repository INTEGER NOT NULL CHECK (scan_limit_per_repository > 0),
  delete_limit_per_repository INTEGER NOT NULL CHECK (delete_limit_per_repository > 0),
  criteria_snapshot_json JSONB NOT NULL,
  repository_snapshot_json JSONB NOT NULL,
  scanned_subjects BIGINT NOT NULL DEFAULT 0 CHECK (scanned_subjects >= 0),
  matched_subjects BIGINT NOT NULL DEFAULT 0 CHECK (matched_subjects >= 0),
  deleted_subjects BIGINT NOT NULL DEFAULT 0 CHECK (deleted_subjects >= 0),
  failed_subjects BIGINT NOT NULL DEFAULT 0 CHECK (failed_subjects >= 0),
  truncated_repositories INTEGER NOT NULL DEFAULT 0 CHECK (truncated_repositories >= 0),
  error_summary VARCHAR(2048),
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_run PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_run_scheduled_fire UNIQUE (policy_id, scheduled_for),
  CONSTRAINT fk_cleanup_run_policy
    FOREIGN KEY (policy_id) REFERENCES cleanup_policy (id) ON DELETE RESTRICT
);

CREATE INDEX idx_cleanup_run_policy ON cleanup_run (policy_id, id);
CREATE INDEX idx_cleanup_run_state ON cleanup_run (state, id);

CREATE TABLE cleanup_run_repository (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  run_id BIGINT NOT NULL CHECK (run_id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  repository_name VARCHAR(200) NOT NULL,
  format VARCHAR(50) NOT NULL,
  repository_type VARCHAR(32) NOT NULL,
  state VARCHAR(32) NOT NULL,
  scanned_subjects BIGINT NOT NULL DEFAULT 0 CHECK (scanned_subjects >= 0),
  matched_subjects BIGINT NOT NULL DEFAULT 0 CHECK (matched_subjects >= 0),
  deleted_subjects BIGINT NOT NULL DEFAULT 0 CHECK (deleted_subjects >= 0),
  failed_subjects BIGINT NOT NULL DEFAULT 0 CHECK (failed_subjects >= 0),
  truncated BOOLEAN NOT NULL DEFAULT FALSE,
  error_summary VARCHAR(2048),
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_run_repository PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_run_repository UNIQUE (run_id, repository_id),
  CONSTRAINT fk_cleanup_run_repository_run
    FOREIGN KEY (run_id) REFERENCES cleanup_run (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_run_repository_run ON cleanup_run_repository (run_id, id);

CREATE TABLE cleanup_run_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  run_repository_id BIGINT NOT NULL CHECK (run_repository_id >= 0),
  subject_kind VARCHAR(32) NOT NULL,
  subject_key VARCHAR(2048) NOT NULL,
  subject_key_hash BYTEA NOT NULL,
  family_key TEXT,
  display_name TEXT NOT NULL,
  version VARCHAR(255),
  delete_path TEXT,
  last_downloaded_at TIMESTAMPTZ(3),
  published_at TIMESTAMPTZ(3),
  asset_count INTEGER NOT NULL DEFAULT 0 CHECK (asset_count >= 0),
  estimated_bytes BIGINT NOT NULL DEFAULT 0 CHECK (estimated_bytes >= 0),
  decision VARCHAR(32) NOT NULL,
  reason_json JSONB NOT NULL,
  error_summary VARCHAR(2048),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_run_item PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_run_item_subject
    UNIQUE (run_repository_id, subject_kind, subject_key_hash),
  CONSTRAINT fk_cleanup_run_item_repository
    FOREIGN KEY (run_repository_id) REFERENCES cleanup_run_repository (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_run_item_repository ON cleanup_run_item (run_repository_id, id);
