ALTER TABLE cleanup_run
  ADD COLUMN cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN cancelled_at TIMESTAMPTZ(3);

ALTER TABLE cleanup_run_repository
  ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  ADD COLUMN max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
  ADD COLUMN scan_budget INTEGER CHECK (scan_budget >= 0),
  ADD COLUMN next_attempt_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN lease_owner VARCHAR(255),
  ADD COLUMN lease_token CHAR(36),
  ADD COLUMN lease_until TIMESTAMPTZ(3),
  ADD COLUMN last_heartbeat_at TIMESTAMPTZ(3),
  ADD COLUMN fencing_token BIGINT NOT NULL DEFAULT 0 CHECK (fencing_token >= 0),
  ADD COLUMN last_error_code VARCHAR(64);

CREATE INDEX idx_cleanup_run_repository_claim
  ON cleanup_run_repository (state, next_attempt_at, lease_until, id);
CREATE INDEX idx_cleanup_run_repository_lease
  ON cleanup_run_repository (lease_until, id);

CREATE INDEX idx_cleanup_run_repository_repository_claim
  ON cleanup_run_repository (repository_id, id, state, next_attempt_at);

ALTER TABLE repository_cleanup_policy
  DROP CONSTRAINT fk_repository_cleanup_policy_repository;

ALTER TABLE repository_cleanup_policy
  ADD CONSTRAINT fk_repository_cleanup_policy_repository
  FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE RESTRICT;

CREATE TABLE cleanup_repository_lease (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  run_repository_id BIGINT,
  lease_owner VARCHAR(255),
  lease_token CHAR(36),
  fencing_token BIGINT NOT NULL DEFAULT 0 CHECK (fencing_token >= 0),
  expires_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_repository_lease PRIMARY KEY (repository_id),
  CONSTRAINT uk_cleanup_repository_lease_shard UNIQUE (run_repository_id),
  CONSTRAINT fk_cleanup_repository_lease_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE,
  CONSTRAINT fk_cleanup_repository_lease_shard
    FOREIGN KEY (run_repository_id) REFERENCES cleanup_run_repository (id) ON DELETE SET NULL
);

CREATE INDEX idx_cleanup_repository_lease_expiry
  ON cleanup_repository_lease (expires_at, repository_id);

INSERT INTO cleanup_repository_lease (repository_id)
SELECT id FROM repository
ON CONFLICT (repository_id) DO NOTHING;

CREATE TABLE cleanup_usage_tracking_repository (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  tracking_started_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_usage_tracking_repository PRIMARY KEY (repository_id),
  CONSTRAINT fk_cleanup_usage_tracking_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE
);

CREATE TABLE cleanup_usage (
  asset_id BIGINT NOT NULL CHECK (asset_id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  first_downloaded_at TIMESTAMPTZ(3) NOT NULL,
  last_downloaded_at TIMESTAMPTZ(3) NOT NULL,
  usage_revision BIGINT NOT NULL DEFAULT 1 CHECK (usage_revision > 0),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_usage PRIMARY KEY (asset_id),
  CONSTRAINT fk_cleanup_usage_asset
    FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE,
  CONSTRAINT fk_cleanup_usage_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_usage_repository
  ON cleanup_usage (repository_id, asset_id);
CREATE INDEX idx_cleanup_usage_last_downloaded
  ON cleanup_usage (repository_id, last_downloaded_at, asset_id);

CREATE TABLE cleanup_protection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  scope VARCHAR(16) NOT NULL,
  repository_id BIGINT,
  subject_kind VARCHAR(32),
  subject_key VARCHAR(2048),
  subject_key_hash BYTEA,
  source VARCHAR(32) NOT NULL,
  external_id VARCHAR(255),
  reason VARCHAR(1024) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at TIMESTAMPTZ(3),
  freshness_at TIMESTAMPTZ(3),
  created_by VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_protection PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_protection_external UNIQUE (source, external_id),
  CONSTRAINT fk_cleanup_protection_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_protection_match
  ON cleanup_protection
    (repository_id, subject_kind, subject_key_hash, enabled, expires_at);
CREATE INDEX idx_cleanup_protection_expiry
  ON cleanup_protection (enabled, expires_at, id);

ALTER TABLE cleanup_run_item
  ADD COLUMN expected_content_token VARCHAR(128),
  ADD COLUMN expected_usage_revision BIGINT NOT NULL DEFAULT 0
    CHECK (expected_usage_revision >= 0),
  ADD COLUMN protection_id BIGINT,
  ADD COLUMN evaluated_at TIMESTAMPTZ(3),
  ADD CONSTRAINT fk_cleanup_run_item_protection
    FOREIGN KEY (protection_id) REFERENCES cleanup_protection (id) ON DELETE SET NULL;
