ALTER TABLE cleanup_policy
  ADD COLUMN revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
  ADD COLUMN state VARCHAR(32) NOT NULL DEFAULT 'PAUSED',
  ADD COLUMN scan_limit_per_repository INTEGER NOT NULL DEFAULT 1000
    CHECK (scan_limit_per_repository > 0),
  ADD COLUMN delete_limit_per_repository INTEGER NOT NULL DEFAULT 100
    CHECK (delete_limit_per_repository > 0);

DROP INDEX uk_cleanup_policy_name;
CREATE UNIQUE INDEX uk_cleanup_policy_active_name
  ON cleanup_policy (name) WHERE state <> 'DELETED';

ALTER TABLE repository_cleanup_policy
  DROP CONSTRAINT fk_repository_cleanup_policy_repository;

ALTER TABLE repository_cleanup_policy
  ADD CONSTRAINT fk_repository_cleanup_policy_repository
  FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE RESTRICT;

CREATE TABLE cleanup_policy_schedule (
  policy_id BIGINT NOT NULL CHECK (policy_id >= 0),
  cron_expression VARCHAR(120) NOT NULL,
  time_zone VARCHAR(64) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_policy_schedule PRIMARY KEY (policy_id),
  CONSTRAINT fk_cleanup_policy_schedule_policy
    FOREIGN KEY (policy_id) REFERENCES cleanup_policy (id) ON DELETE CASCADE
);

CREATE TABLE cleanup_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  policy_id BIGINT NOT NULL CHECK (policy_id >= 0),
  policy_revision BIGINT NOT NULL CHECK (policy_revision > 0),
  mode VARCHAR(16) NOT NULL,
  trigger_kind VARCHAR(16) NOT NULL,
  state VARCHAR(32) NOT NULL,
  cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
  requested_by VARCHAR(255) NOT NULL,
  scheduled_for TIMESTAMPTZ(3),
  scan_limit_per_repository INTEGER NOT NULL CHECK (scan_limit_per_repository > 0),
  delete_limit_per_repository INTEGER NOT NULL CHECK (delete_limit_per_repository > 0),
  criteria_snapshot_json JSONB NOT NULL,
  repository_snapshot_json JSONB NOT NULL,
  scanned_subjects BIGINT NOT NULL DEFAULT 0 CHECK (scanned_subjects >= 0),
  matched_subjects BIGINT NOT NULL DEFAULT 0 CHECK (matched_subjects >= 0),
  would_delete_subjects BIGINT NOT NULL DEFAULT 0 CHECK (would_delete_subjects >= 0),
  deleted_subjects BIGINT NOT NULL DEFAULT 0 CHECK (deleted_subjects >= 0),
  failed_subjects BIGINT NOT NULL DEFAULT 0 CHECK (failed_subjects >= 0),
  truncated_repositories INTEGER NOT NULL DEFAULT 0 CHECK (truncated_repositories >= 0),
  error_summary VARCHAR(2048),
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  cancelled_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_run PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_run_scheduled_fire UNIQUE (policy_id, scheduled_for),
  CONSTRAINT fk_cleanup_run_policy
    FOREIGN KEY (policy_id) REFERENCES cleanup_policy (id) ON DELETE RESTRICT
);

CREATE INDEX idx_cleanup_run_policy ON cleanup_run (policy_id, id);
CREATE INDEX idx_cleanup_run_state ON cleanup_run (state, id);
CREATE INDEX idx_cleanup_run_retention ON cleanup_run (state, completed_at, id);

CREATE TABLE cleanup_run_repository (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  run_id BIGINT NOT NULL CHECK (run_id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  repository_name VARCHAR(200) NOT NULL,
  format VARCHAR(50) NOT NULL,
  repository_type VARCHAR(32) NOT NULL,
  state VARCHAR(32) NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
  scan_budget INTEGER CHECK (scan_budget >= 0),
  scan_cursor_phase VARCHAR(16),
  scan_cursor_component_namespace VARCHAR(512),
  scan_cursor_component_name VARCHAR(512),
  scan_cursor_component_kind VARCHAR(50),
  scan_cursor_subject_id BIGINT CHECK (scan_cursor_subject_id >= 0),
  scan_cursor_revision BIGINT CHECK (scan_cursor_revision >= 0),
  scan_cursor_wrapped_count BIGINT CHECK (scan_cursor_wrapped_count >= 0),
  next_attempt_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lease_owner VARCHAR(255),
  lease_token CHAR(36),
  lease_until TIMESTAMPTZ(3),
  last_heartbeat_at TIMESTAMPTZ(3),
  fencing_token BIGINT NOT NULL DEFAULT 0 CHECK (fencing_token >= 0),
  scanned_subjects BIGINT NOT NULL DEFAULT 0 CHECK (scanned_subjects >= 0),
  matched_subjects BIGINT NOT NULL DEFAULT 0 CHECK (matched_subjects >= 0),
  would_delete_subjects BIGINT NOT NULL DEFAULT 0 CHECK (would_delete_subjects >= 0),
  deleted_subjects BIGINT NOT NULL DEFAULT 0 CHECK (deleted_subjects >= 0),
  failed_subjects BIGINT NOT NULL DEFAULT 0 CHECK (failed_subjects >= 0),
  truncated BOOLEAN NOT NULL DEFAULT FALSE,
  error_summary VARCHAR(2048),
  last_error_code VARCHAR(64),
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_run_repository PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_run_repository UNIQUE (run_id, repository_id),
  CONSTRAINT fk_cleanup_run_repository_run
    FOREIGN KEY (run_id) REFERENCES cleanup_run (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_run_repository_run ON cleanup_run_repository (run_id, id);
CREATE INDEX idx_cleanup_run_repository_claim
  ON cleanup_run_repository (state, next_attempt_at, lease_until, id);
CREATE INDEX idx_cleanup_run_repository_lease
  ON cleanup_run_repository (lease_until, id);
CREATE INDEX idx_cleanup_run_repository_repository_claim
  ON cleanup_run_repository (repository_id, id, state, next_attempt_at);
CREATE INDEX idx_cleanup_run_repository_operational
  ON cleanup_run_repository (state, created_at, lease_until, id);

CREATE TABLE cleanup_repository_lease (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  run_repository_id BIGINT,
  lease_owner VARCHAR(255),
  lease_token CHAR(36),
  fencing_token BIGINT NOT NULL DEFAULT 0 CHECK (fencing_token >= 0),
  expires_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_repository_lease PRIMARY KEY (repository_id),
  CONSTRAINT uk_cleanup_repository_lease_shard UNIQUE (run_repository_id),
  CONSTRAINT fk_cleanup_repository_lease_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE,
  CONSTRAINT fk_cleanup_repository_lease_shard
    FOREIGN KEY (run_repository_id) REFERENCES cleanup_run_repository (id) ON DELETE SET NULL
);

CREATE INDEX idx_cleanup_repository_lease_expiry
  ON cleanup_repository_lease (expires_at, repository_id);

CREATE TABLE cleanup_usage_tracking_repository (
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  tracking_started_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_usage_tracking_repository PRIMARY KEY (repository_id),
  CONSTRAINT fk_cleanup_usage_tracking_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE
);

CREATE TABLE cleanup_usage (
  asset_id BIGINT NOT NULL CHECK (asset_id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  first_downloaded_at TIMESTAMPTZ(3) NOT NULL,
  last_downloaded_at TIMESTAMPTZ(3) NOT NULL,
  usage_revision BIGINT NOT NULL DEFAULT 1 CHECK (usage_revision > 0),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_usage PRIMARY KEY (asset_id),
  CONSTRAINT fk_cleanup_usage_asset
    FOREIGN KEY (asset_id) REFERENCES asset (id) ON DELETE CASCADE,
  CONSTRAINT fk_cleanup_usage_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_usage_repository
  ON cleanup_usage (repository_id, asset_id);
CREATE INDEX idx_cleanup_usage_last_downloaded
  ON cleanup_usage (repository_id, last_downloaded_at, asset_id);

CREATE TABLE cleanup_protection (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  scope VARCHAR(16) NOT NULL,
  repository_id BIGINT,
  subject_kind VARCHAR(32),
  subject_key VARCHAR(2048),
  subject_key_hash BYTEA,
  source VARCHAR(32) NOT NULL,
  external_id VARCHAR(255),
  reason VARCHAR(1024) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at TIMESTAMPTZ(3),
  freshness_at TIMESTAMPTZ(3),
  created_by VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_protection PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_protection_external UNIQUE (source, external_id),
  CONSTRAINT fk_cleanup_protection_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_protection_match
  ON cleanup_protection
    (repository_id, subject_kind, subject_key_hash, enabled, expires_at);
CREATE INDEX idx_cleanup_protection_expiry
  ON cleanup_protection (enabled, expires_at, id);

CREATE TABLE cleanup_run_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL CHECK (id >= 0),
  run_repository_id BIGINT NOT NULL CHECK (run_repository_id >= 0),
  subject_kind VARCHAR(32) NOT NULL,
  subject_key VARCHAR(2048) NOT NULL,
  subject_key_hash BYTEA NOT NULL,
  family_key TEXT,
  display_name TEXT NOT NULL,
  version VARCHAR(255),
  delete_path TEXT,
  last_downloaded_at TIMESTAMPTZ(3),
  published_at TIMESTAMPTZ(3),
  asset_count INTEGER NOT NULL DEFAULT 0 CHECK (asset_count >= 0),
  estimated_bytes BIGINT NOT NULL DEFAULT 0 CHECK (estimated_bytes >= 0),
  expected_content_token VARCHAR(128),
  expected_usage_revision BIGINT NOT NULL DEFAULT 0
    CHECK (expected_usage_revision >= 0),
  protection_id BIGINT,
  evaluated_at TIMESTAMPTZ(3),
  decision VARCHAR(32) NOT NULL,
  reason_json JSONB NOT NULL,
  error_summary VARCHAR(2048),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_run_item PRIMARY KEY (id),
  CONSTRAINT uk_cleanup_run_item_subject
    UNIQUE (run_repository_id, subject_kind, subject_key_hash),
  CONSTRAINT fk_cleanup_run_item_repository
    FOREIGN KEY (run_repository_id) REFERENCES cleanup_run_repository (id) ON DELETE CASCADE,
  CONSTRAINT fk_cleanup_run_item_protection
    FOREIGN KEY (protection_id) REFERENCES cleanup_protection (id) ON DELETE SET NULL
);

CREATE INDEX idx_cleanup_run_item_repository ON cleanup_run_item (run_repository_id, id);

CREATE TABLE cleanup_policy_repository_cursor (
  policy_id BIGINT NOT NULL CHECK (policy_id >= 0),
  repository_id BIGINT NOT NULL CHECK (repository_id >= 0),
  phase VARCHAR(16) NOT NULL,
  component_namespace VARCHAR(512),
  component_name VARCHAR(512),
  component_kind VARCHAR(50),
  subject_id BIGINT NOT NULL DEFAULT 0 CHECK (subject_id >= 0),
  revision BIGINT NOT NULL DEFAULT 0 CHECK (revision >= 0),
  wrapped_count BIGINT NOT NULL DEFAULT 0 CHECK (wrapped_count >= 0),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cleanup_policy_repository_cursor PRIMARY KEY (policy_id, repository_id),
  CONSTRAINT fk_cleanup_policy_repository_cursor_policy
    FOREIGN KEY (policy_id) REFERENCES cleanup_policy (id) ON DELETE CASCADE,
  CONSTRAINT fk_cleanup_policy_repository_cursor_repository
    FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE
);

CREATE INDEX idx_cleanup_policy_repository_cursor_repository
  ON cleanup_policy_repository_cursor (repository_id, policy_id);

INSERT INTO cache_version (name, version, updated_at)
VALUES ('cleanup-usage-tracking', 0, CURRENT_TIMESTAMP)
ON CONFLICT (name) DO NOTHING;
