CREATE TABLE conda_package_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  channel_key VARCHAR(512) NOT NULL,
  channel_key_hash BYTEA NOT NULL,
  subdir VARCHAR(32) NOT NULL,
  filename VARCHAR(211) NOT NULL,
  name VARCHAR(64) NOT NULL,
  version VARCHAR(64) NOT NULL,
  build_string VARCHAR(64) NOT NULL,
  build_number BIGINT NOT NULL,
  archive_format VARCHAR(16) NOT NULL,
  record_json JSONB NOT NULL,
  record_sha256 CHAR(64),
  md5 CHAR(32),
  sha256 CHAR(64),
  size_bytes BIGINT NOT NULL,
  asset_id BIGINT REFERENCES asset(id) ON DELETE CASCADE,
  component_id BIGINT REFERENCES component(id) ON DELETE SET NULL,
  source_kind VARCHAR(16) NOT NULL,
  revision BIGINT NOT NULL,
  indexed_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conda_package_path
    UNIQUE (repository_id, channel_key_hash, subdir, filename),
  CONSTRAINT ck_conda_package_build_number_nonnegative CHECK (build_number >= 0),
  CONSTRAINT ck_conda_package_size_nonnegative CHECK (size_bytes >= 0)
);
CREATE INDEX idx_conda_package_coordinate
  ON conda_package_record(repository_id, channel_key_hash, subdir, name, version, build_string);
CREATE INDEX idx_conda_package_channel_name
  ON conda_package_record(repository_id, channel_key_hash, name, subdir, filename);
CREATE INDEX idx_conda_package_metadata
  ON conda_package_record(repository_id, channel_key_hash, subdir, archive_format, filename);
CREATE INDEX idx_conda_package_revision ON conda_package_record(repository_id, revision);

CREATE TABLE conda_channel_state (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  channel_key VARCHAR(512) NOT NULL,
  channel_key_hash BYTEA NOT NULL,
  subdir VARCHAR(32) NOT NULL,
  metadata_sha256 CHAR(64),
  package_base_url VARCHAR(2048),
  revision BIGINT NOT NULL,
  indexed_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, channel_key_hash, subdir)
);
CREATE INDEX idx_conda_channel_revision ON conda_channel_state(repository_id, revision);

CREATE TABLE conda_package_tombstone (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  channel_key VARCHAR(512) NOT NULL,
  channel_key_hash BYTEA NOT NULL,
  subdir VARCHAR(32) NOT NULL,
  filename VARCHAR(211) NOT NULL,
  reason VARCHAR(255),
  revision BIGINT NOT NULL,
  deleted_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, channel_key_hash, subdir, filename)
);
CREATE INDEX idx_conda_tombstone_revision
  ON conda_package_tombstone(repository_id, revision);

CREATE TABLE conda_group_source_binding (
  group_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  channel_key VARCHAR(512) NOT NULL,
  channel_key_hash BYTEA NOT NULL,
  subdir VARCHAR(32) NOT NULL,
  filename VARCHAR(211) NOT NULL,
  member_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  member_revision BIGINT NOT NULL,
  sha256 VARCHAR(64) NOT NULL,
  group_config_revision BIGINT NOT NULL,
  bound_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (group_repository_id, channel_key_hash, subdir, filename)
);
CREATE INDEX idx_conda_group_member
  ON conda_group_source_binding(member_repository_id, member_revision);

CREATE TABLE conda_coordinate_lease (
  lease_key VARCHAR(512) PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  attempt_count BIGINT NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_conda_lease_expiry ON conda_coordinate_lease(expires_at);
