CREATE TABLE apt_package_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  coordinate_hash BYTEA NOT NULL,
  distribution_name VARCHAR(128) NOT NULL,
  component_name VARCHAR(128) NOT NULL,
  architecture VARCHAR(64) NOT NULL,
  package_name VARCHAR(128) NOT NULL,
  package_version VARCHAR(255) NOT NULL,
  source_package VARCHAR(255),
  filename VARCHAR(255) NOT NULL,
  asset_path VARCHAR(1024) NOT NULL,
  control_fields JSONB NOT NULL,
  md5 CHAR(32) NOT NULL,
  sha1 CHAR(40) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  asset_id BIGINT REFERENCES asset(id) ON DELETE CASCADE,
  component_id BIGINT REFERENCES component(id) ON DELETE SET NULL,
  source_kind VARCHAR(16) NOT NULL,
  revision BIGINT NOT NULL,
  indexed_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_apt_package_coordinate UNIQUE (repository_id, coordinate_hash),
  CONSTRAINT uk_apt_package_asset UNIQUE (repository_id, asset_id)
);
CREATE INDEX idx_apt_package_index
  ON apt_package_record(repository_id, distribution_name, component_name, architecture, package_name);
CREATE INDEX idx_apt_package_path ON apt_package_record(repository_id, asset_path);
CREATE INDEX idx_apt_package_revision ON apt_package_record(repository_id, revision);

CREATE TABLE apt_package_tombstone (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  coordinate_hash BYTEA NOT NULL,
  distribution_name VARCHAR(128) NOT NULL,
  component_name VARCHAR(128) NOT NULL,
  architecture VARCHAR(64) NOT NULL,
  package_name VARCHAR(128) NOT NULL,
  package_version VARCHAR(255) NOT NULL,
  asset_path VARCHAR(1024) NOT NULL,
  reason VARCHAR(255),
  revision BIGINT NOT NULL,
  deleted_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, coordinate_hash)
);
CREATE INDEX idx_apt_tombstone_revision ON apt_package_tombstone(repository_id, revision);

CREATE TABLE apt_suite_state (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(128) NOT NULL,
  desired_revision BIGINT NOT NULL DEFAULT 0,
  desired_at TIMESTAMPTZ(3) NOT NULL,
  published_revision BIGINT NOT NULL DEFAULT 0,
  signing_key_revision INTEGER NOT NULL DEFAULT 0,
  last_published_at TIMESTAMPTZ(3),
  last_error VARCHAR(2048),
  last_error_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, distribution_name)
);
CREATE INDEX idx_apt_suite_pending
  ON apt_suite_state(repository_id, desired_revision, published_revision);

CREATE TABLE apt_snapshot (
  repository_id BIGINT NOT NULL,
  distribution_name VARCHAR(128) NOT NULL,
  revision BIGINT NOT NULL,
  signing_key_revision INTEGER NOT NULL,
  manifest_json JSONB NOT NULL,
  release_sha256 CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL,
  published_at TIMESTAMPTZ(3),
  PRIMARY KEY (repository_id, distribution_name, revision),
  CONSTRAINT fk_apt_snapshot_suite
    FOREIGN KEY (repository_id, distribution_name)
    REFERENCES apt_suite_state(repository_id, distribution_name) ON DELETE CASCADE
);
CREATE INDEX idx_apt_snapshot_created
  ON apt_snapshot(repository_id, distribution_name, created_at);

CREATE TABLE apt_signing_key (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  revision INTEGER NOT NULL,
  key_id VARCHAR(32) NOT NULL,
  fingerprint VARCHAR(64) NOT NULL,
  encrypted_private_key TEXT NOT NULL,
  public_key TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, revision)
);
CREATE INDEX idx_apt_signing_active ON apt_signing_key(repository_id, active, revision);

CREATE TABLE apt_proxy_distribution (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(128) NOT NULL,
  release_identity VARCHAR(128),
  release_manifest_json JSONB NOT NULL,
  signature_verified BOOLEAN NOT NULL DEFAULT FALSE,
  observed_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, distribution_name)
);

CREATE TABLE apt_publish_lease (
  lease_key VARCHAR(512) PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  attempt_count BIGINT NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_apt_lease_expiry ON apt_publish_lease(expires_at);
