CREATE TABLE conan_recipe (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  component_id BIGINT REFERENCES component(id) ON DELETE SET NULL,
  coordinate_hash BYTEA NOT NULL,
  name_key VARCHAR(101) NOT NULL,
  version_key VARCHAR(101) NOT NULL,
  user_key VARCHAR(101) NOT NULL DEFAULT '',
  channel_key VARCHAR(101) NOT NULL DEFAULT '',
  latest_recipe_revision_id BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_recipe_coordinate UNIQUE (repository_id, coordinate_hash)
);
CREATE INDEX idx_conan_recipe_search
  ON conan_recipe(repository_id, name_key, user_key, channel_key, version_key, id);
CREATE INDEX idx_conan_recipe_page ON conan_recipe(repository_id, id);
CREATE INDEX idx_conan_recipe_name_page ON conan_recipe(repository_id, name_key, id);
CREATE INDEX idx_conan_recipe_component ON conan_recipe(repository_id, component_id);

CREATE TABLE conan_recipe_revision (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id BIGINT NOT NULL REFERENCES conan_recipe(id) ON DELETE CASCADE,
  rrev VARCHAR(128) NOT NULL,
  rrev_hash BYTEA NOT NULL,
  manifest_sha256 CHAR(64),
  source_kind VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  repository_revision BIGINT NOT NULL,
  published_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_rrev UNIQUE (recipe_id, rrev_hash)
);
CREATE INDEX idx_conan_rrev_list ON conan_recipe_revision(recipe_id, published_at, id);
CREATE INDEX idx_conan_rrev_page ON conan_recipe_revision(recipe_id, id);
CREATE INDEX idx_conan_rrev_repository_revision
  ON conan_recipe_revision(repository_revision, id);
ALTER TABLE conan_recipe ADD CONSTRAINT fk_conan_recipe_latest_rrev
  FOREIGN KEY (latest_recipe_revision_id) REFERENCES conan_recipe_revision(id)
  ON DELETE SET NULL;

CREATE TABLE conan_package (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_revision_id BIGINT NOT NULL REFERENCES conan_recipe_revision(id) ON DELETE CASCADE,
  package_id VARCHAR(128) NOT NULL,
  package_id_hash BYTEA NOT NULL,
  settings_json JSONB NOT NULL,
  options_json JSONB NOT NULL,
  requires_json JSONB NOT NULL,
  setting_os VARCHAR(128),
  setting_arch VARCHAR(128),
  setting_compiler VARCHAR(128),
  setting_compiler_version VARCHAR(128),
  setting_build_type VARCHAR(128),
  latest_package_revision_id BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_package UNIQUE (recipe_revision_id, package_id_hash)
);
CREATE INDEX idx_conan_package_list ON conan_package(recipe_revision_id, id);
CREATE INDEX idx_conan_package_os ON conan_package(recipe_revision_id, setting_os, id);
CREATE INDEX idx_conan_package_arch ON conan_package(recipe_revision_id, setting_arch, id);
CREATE INDEX idx_conan_package_compiler
  ON conan_package(recipe_revision_id, setting_compiler, setting_compiler_version, id);
CREATE INDEX idx_conan_package_build_type
  ON conan_package(recipe_revision_id, setting_build_type, id);

CREATE TABLE conan_package_revision (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conan_package_id BIGINT NOT NULL REFERENCES conan_package(id) ON DELETE CASCADE,
  prev_value VARCHAR(128) NOT NULL,
  prev_hash BYTEA NOT NULL,
  manifest_sha256 CHAR(64),
  source_kind VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  repository_revision BIGINT NOT NULL,
  published_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_prev UNIQUE (conan_package_id, prev_hash)
);
CREATE INDEX idx_conan_prev_list
  ON conan_package_revision(conan_package_id, published_at, id);
CREATE INDEX idx_conan_prev_page ON conan_package_revision(conan_package_id, id);
CREATE INDEX idx_conan_prev_repository_revision
  ON conan_package_revision(repository_revision, id);
ALTER TABLE conan_package ADD CONSTRAINT fk_conan_package_latest_prev
  FOREIGN KEY (latest_package_revision_id) REFERENCES conan_package_revision(id)
  ON DELETE SET NULL;

CREATE TABLE conan_revision_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_kind VARCHAR(16) NOT NULL,
  owner_id BIGINT NOT NULL,
  path_value VARCHAR(1024) NOT NULL,
  path_hash BYTEA NOT NULL,
  asset_id BIGINT UNIQUE REFERENCES asset(id) ON DELETE CASCADE,
  md5 CHAR(32),
  sha1 CHAR(40),
  sha256 CHAR(64),
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  content_type VARCHAR(255),
  source_repository_id BIGINT REFERENCES repository(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_revision_file UNIQUE (owner_kind, owner_id, path_hash)
);
CREATE INDEX idx_conan_file_list ON conan_revision_file(owner_kind, owner_id, id);
CREATE INDEX idx_conan_file_source
  ON conan_revision_file(source_repository_id, owner_kind, owner_id);

CREATE TABLE conan_repository_state (
  repository_id BIGINT PRIMARY KEY REFERENCES repository(id) ON DELETE CASCADE,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE conan_upload_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  owner_kind VARCHAR(16) NOT NULL,
  coordinate_key VARCHAR(2048) NOT NULL,
  coordinate_hash BYTEA NOT NULL,
  actor_key VARCHAR(512) NOT NULL,
  actor_hash BYTEA NOT NULL,
  status VARCHAR(16) NOT NULL,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL DEFAULT 0,
  lease_until TIMESTAMPTZ(3),
  expires_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_upload_session
    UNIQUE (repository_id, owner_kind, coordinate_hash, actor_hash)
);
CREATE INDEX idx_conan_upload_claim ON conan_upload_session(status, lease_until, id);
CREATE INDEX idx_conan_upload_expiry ON conan_upload_session(expires_at, id);

CREATE TABLE conan_upload_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES conan_upload_session(id) ON DELETE CASCADE,
  path_value VARCHAR(1024) NOT NULL,
  path_hash BYTEA NOT NULL,
  staging_asset_id BIGINT NOT NULL UNIQUE REFERENCES asset(id) ON DELETE CASCADE,
  md5 CHAR(32) NOT NULL,
  sha1 CHAR(40) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  content_type VARCHAR(255),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_upload_file UNIQUE (session_id, path_hash)
);
CREATE INDEX idx_conan_upload_file_list ON conan_upload_file(session_id, id);

CREATE TABLE conan_coordinate_lease (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  coordinate_key VARCHAR(2048) NOT NULL,
  coordinate_hash BYTEA NOT NULL,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, coordinate_hash)
);
CREATE INDEX idx_conan_lease_expiry ON conan_coordinate_lease(expires_at);

CREATE TABLE conan_group_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  binding_kind VARCHAR(16) NOT NULL,
  coordinate_key VARCHAR(2048) NOT NULL,
  coordinate_hash BYTEA NOT NULL,
  member_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  member_owner_id BIGINT NOT NULL,
  member_revision BIGINT NOT NULL,
  group_config_revision BIGINT NOT NULL,
  expires_at TIMESTAMPTZ(3),
  bound_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_conan_group_binding
    UNIQUE (group_repository_id, binding_kind, coordinate_hash)
);
CREATE INDEX idx_conan_group_member
  ON conan_group_binding(member_repository_id, member_revision, id);
CREATE INDEX idx_conan_group_expiry ON conan_group_binding(expires_at, id);

CREATE TABLE conan_auth_token (
  token_hash CHAR(64) PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  subject_source VARCHAR(128) NOT NULL,
  subject_user_id VARCHAR(255) NOT NULL,
  realm_id VARCHAR(255),
  api_key_id BIGINT,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  last_used_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_conan_token_expiry ON conan_auth_token(expires_at, token_hash);
CREATE INDEX idx_conan_token_subject
  ON conan_auth_token(subject_source, subject_user_id, token_hash);
