CREATE TABLE alpine_package_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  coordinate_hash BYTEA NOT NULL,
  distribution_name VARCHAR(384) NOT NULL,
  component_name VARCHAR(128) NOT NULL,
  architecture VARCHAR(64) NOT NULL,
  package_name VARCHAR(128) NOT NULL,
  package_version VARCHAR(255) NOT NULL,
  package_architecture VARCHAR(255) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  asset_path VARCHAR(1024) NOT NULL,
  control_fields JSONB NOT NULL,
  package_identity VARCHAR(64) NOT NULL,
  data_sha256 CHAR(64) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  asset_id BIGINT REFERENCES asset(id) ON DELETE CASCADE,
  component_id BIGINT REFERENCES component(id) ON DELETE SET NULL,
  source_kind VARCHAR(16) NOT NULL,
  revision BIGINT NOT NULL,
  indexed_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_alpine_package_coordinate UNIQUE (repository_id, coordinate_hash),
  CONSTRAINT uk_alpine_package_path UNIQUE (repository_id, asset_path),
  CONSTRAINT uk_alpine_package_asset UNIQUE (repository_id, asset_id),
  CONSTRAINT chk_alpine_package_source CHECK (source_kind IN ('HOSTED', 'PROXY'))
);
CREATE INDEX idx_alpine_package_index
  ON alpine_package_record(
    repository_id, distribution_name, component_name, architecture, package_name, id);
CREATE INDEX idx_alpine_package_path ON alpine_package_record(repository_id, asset_path);

CREATE TABLE alpine_package_tombstone (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  coordinate_hash BYTEA NOT NULL,
  distribution_name VARCHAR(384) NOT NULL,
  component_name VARCHAR(128) NOT NULL,
  architecture VARCHAR(64) NOT NULL,
  package_name VARCHAR(128) NOT NULL,
  package_version VARCHAR(255) NOT NULL,
  asset_path VARCHAR(1024) NOT NULL,
  reason VARCHAR(255),
  revision BIGINT NOT NULL,
  deleted_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, coordinate_hash)
);
CREATE INDEX idx_alpine_tombstone_revision ON alpine_package_tombstone(repository_id, revision);

CREATE TABLE alpine_suite_state (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(384) NOT NULL,
  desired_revision BIGINT NOT NULL DEFAULT 0,
  desired_at TIMESTAMPTZ(3) NOT NULL,
  pending_since TIMESTAMPTZ(3),
  published_revision BIGINT NOT NULL DEFAULT 0,
  signing_key_revision INTEGER NOT NULL DEFAULT 0,
  last_published_at TIMESTAMPTZ(3),
  last_error VARCHAR(2048),
  last_error_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, distribution_name)
);
CREATE INDEX idx_alpine_suite_pending
  ON alpine_suite_state(repository_id, desired_revision, published_revision);

CREATE TABLE alpine_snapshot (
  repository_id BIGINT NOT NULL,
  distribution_name VARCHAR(384) NOT NULL,
  revision BIGINT NOT NULL,
  signing_key_revision INTEGER NOT NULL,
  manifest_json JSONB NOT NULL,
  index_sha256 CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL,
  published_at TIMESTAMPTZ(3),
  PRIMARY KEY (repository_id, distribution_name, revision),
  CONSTRAINT fk_alpine_snapshot_suite
    FOREIGN KEY (repository_id, distribution_name)
    REFERENCES alpine_suite_state(repository_id, distribution_name) ON DELETE CASCADE
);
CREATE INDEX idx_alpine_snapshot_created
  ON alpine_snapshot(repository_id, distribution_name, created_at);

CREATE TABLE alpine_signing_key (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  revision INTEGER NOT NULL,
  key_filename VARCHAR(192) NOT NULL,
  fingerprint VARCHAR(64) NOT NULL,
  encrypted_private_key TEXT NOT NULL,
  public_key TEXT NOT NULL,
  signature_type VARCHAR(16) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, revision)
);
CREATE INDEX idx_alpine_signing_active ON alpine_signing_key(repository_id, active, revision);
CREATE UNIQUE INDEX uk_alpine_signing_active
  ON alpine_signing_key(repository_id) WHERE active;
ALTER TABLE alpine_signing_key
  ADD CONSTRAINT chk_alpine_signature_type
  CHECK (signature_type IN ('RSA', 'RSA256', 'RSA512'));

CREATE TABLE alpine_proxy_distribution (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(384) NOT NULL,
  release_identity VARCHAR(128),
  release_manifest_json JSONB NOT NULL,
  signature_verified BOOLEAN NOT NULL DEFAULT FALSE,
  observed_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, distribution_name)
);

CREATE TABLE alpine_publish_lease (
  lease_key VARCHAR(512) PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  attempt_count BIGINT NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_alpine_lease_expiry ON alpine_publish_lease(expires_at);

CREATE TABLE alpine_package_relation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT NOT NULL REFERENCES alpine_package_record(id) ON DELETE CASCADE,
  relation_kind VARCHAR(16) NOT NULL,
  token_value VARCHAR(512) NOT NULL,
  token_hash BYTEA NOT NULL,
  expression_value VARCHAR(1024) NOT NULL,
  CONSTRAINT uk_alpine_relation UNIQUE (package_id, relation_kind, token_hash)
);
CREATE INDEX idx_alpine_relation_lookup
  ON alpine_package_relation(relation_kind, token_hash, package_id);

CREATE TABLE alpine_group_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(384) NOT NULL,
  snapshot_revision BIGINT NOT NULL,
  path_value VARCHAR(1024) NOT NULL,
  path_hash BYTEA NOT NULL,
  member_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  member_snapshot_revision BIGINT NOT NULL,
  member_path VARCHAR(1024) NOT NULL,
  package_identity VARCHAR(64) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  created_at TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT uk_alpine_group_binding
    UNIQUE (group_repository_id, distribution_name, snapshot_revision, path_hash)
);
CREATE INDEX idx_alpine_group_member
  ON alpine_group_binding(member_repository_id, member_snapshot_revision, id);
CREATE INDEX idx_alpine_group_page
  ON alpine_group_binding(group_repository_id, distribution_name, snapshot_revision, id);

CREATE INDEX idx_alpine_tombstone_cleanup
  ON alpine_package_tombstone(deleted_at, repository_id, revision);
CREATE INDEX idx_alpine_suite_worker
  ON alpine_suite_state(desired_at, last_error_at, repository_id)
  WHERE desired_revision > published_revision;
CREATE INDEX idx_alpine_suite_force_publish
  ON alpine_suite_state(pending_since, repository_id)
  WHERE desired_revision > published_revision;
CREATE INDEX idx_alpine_snapshot_cleanup
  ON alpine_snapshot(published_at, created_at, repository_id, distribution_name)
  WHERE published_at IS NOT NULL;
