CREATE TABLE huggingface_model_revision (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  repo_id VARCHAR(193) NOT NULL,
  repo_id_hash BYTEA NOT NULL,
  commit_hash VARCHAR(64) NOT NULL,
  component_id BIGINT UNIQUE REFERENCES component(id) ON DELETE SET NULL,
  raw_metadata_asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  author_name VARCHAR(255),
  committed_at TIMESTAMPTZ(3),
  private_model BOOLEAN NOT NULL DEFAULT FALSE,
  gated_model BOOLEAN NOT NULL DEFAULT FALSE,
  library_name VARCHAR(128),
  pipeline_tag VARCHAR(128),
  license_name VARCHAR(128),
  observed_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_hf_revision_identity UNIQUE (repository_id, repo_id_hash, commit_hash)
);
CREATE INDEX idx_hf_revision_page
  ON huggingface_model_revision(repository_id, repo_id_hash, observed_at, id);
CREATE INDEX idx_hf_revision_commit
  ON huggingface_model_revision(repository_id, commit_hash, id);

CREATE TABLE huggingface_revision_ref (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  repo_id VARCHAR(193) NOT NULL,
  repo_id_hash BYTEA NOT NULL,
  requested_ref VARCHAR(255) NOT NULL,
  ref_hash BYTEA NOT NULL,
  commit_hash VARCHAR(64) NOT NULL,
  binding_generation BIGINT NOT NULL CHECK (binding_generation > 0),
  expires_at TIMESTAMPTZ(3) NOT NULL,
  observed_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, repo_id_hash, ref_hash)
);
CREATE INDEX idx_hf_ref_expiry
  ON huggingface_revision_ref(expires_at, repository_id);
CREATE INDEX idx_hf_ref_commit
  ON huggingface_revision_ref(repository_id, repo_id_hash, commit_hash);

CREATE TABLE huggingface_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revision_id BIGINT NOT NULL REFERENCES huggingface_model_revision(id) ON DELETE CASCADE,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  repo_id VARCHAR(193) NOT NULL,
  repo_id_hash BYTEA NOT NULL,
  commit_hash VARCHAR(64) NOT NULL,
  file_path VARCHAR(2048) NOT NULL,
  path_hash BYTEA NOT NULL,
  asset_id BIGINT UNIQUE REFERENCES asset(id) ON DELETE SET NULL,
  component_id BIGINT REFERENCES component(id) ON DELETE SET NULL,
  git_oid VARCHAR(64),
  lfs_sha256 CHAR(64),
  xet_hash VARCHAR(256),
  expected_size BIGINT CHECK (expected_size IS NULL OR expected_size >= 0),
  internal_sha256 CHAR(64),
  content_type VARCHAR(255),
  file_kind VARCHAR(32) NOT NULL,
  file_state VARCHAR(16) NOT NULL,
  fencing_token BIGINT NOT NULL DEFAULT 0,
  failure_code VARCHAR(64),
  next_attempt_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_hf_file_identity
    UNIQUE (repository_id, repo_id_hash, commit_hash, path_hash)
);
CREATE INDEX idx_hf_file_page ON huggingface_file(revision_id, id);
CREATE INDEX idx_hf_file_state ON huggingface_file(file_state, next_attempt_at, id);
CREATE INDEX idx_hf_file_component ON huggingface_file(component_id, id);

CREATE TABLE huggingface_api_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  route_path TEXT NOT NULL,
  route_hash BYTEA NOT NULL,
  query_string TEXT NOT NULL,
  query_hash BYTEA NOT NULL,
  request_fingerprint VARCHAR(128) NOT NULL,
  request_hash BYTEA NOT NULL,
  raw_asset_id BIGINT REFERENCES asset(id) ON DELETE SET NULL,
  derived_asset_id BIGINT UNIQUE REFERENCES asset(id) ON DELETE SET NULL,
  upstream_etag VARCHAR(255),
  derived_etag VARCHAR(128),
  next_link TEXT,
  transform_version INT NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_hf_api_identity
    UNIQUE (repository_id, route_hash, query_hash, request_hash)
);
CREATE INDEX idx_hf_api_expiry ON huggingface_api_cache(expires_at, id);

CREATE TABLE huggingface_route_projection (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  route_path TEXT NOT NULL,
  route_hash BYTEA NOT NULL,
  file_id BIGINT NOT NULL REFERENCES huggingface_file(id) ON DELETE CASCADE,
  requested_ref VARCHAR(255) NOT NULL,
  ref_generation BIGINT NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, route_hash)
);
CREATE INDEX idx_hf_projection_file
  ON huggingface_route_projection(file_id, repository_id);

CREATE TABLE proxy_fetch_lease (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  fetch_key TEXT NOT NULL,
  fetch_key_hash BYTEA NOT NULL,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  attempt_count BIGINT NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, fetch_key_hash)
);
CREATE INDEX idx_proxy_fetch_lease_expiry
  ON proxy_fetch_lease(expires_at, repository_id);
