CREATE TABLE r_package_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  coordinate_hash BYTEA NOT NULL,
  distribution_name VARCHAR(384) NOT NULL,
  component_name VARCHAR(128) NOT NULL,
  architecture VARCHAR(64) NOT NULL,
  package_name VARCHAR(128) NOT NULL,
  package_version VARCHAR(255) NOT NULL,
  version_order_key BYTEA NOT NULL,
  package_architecture VARCHAR(255) NOT NULL,
  filename VARCHAR(255) NOT NULL,
  asset_path VARCHAR(1024) NOT NULL,
  asset_path_hash BYTEA NOT NULL,
  control_fields JSONB NOT NULL,
  package_identity VARCHAR(64) NOT NULL,
  data_sha256 CHAR(64) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  asset_id BIGINT REFERENCES asset(id) ON DELETE CASCADE,
  component_id BIGINT REFERENCES component(id) ON DELETE SET NULL,
  source_kind VARCHAR(16) NOT NULL,
  revision BIGINT NOT NULL,
  indexed_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_r_package_repository_id UNIQUE (repository_id, id),
  CONSTRAINT uk_r_package_coordinate UNIQUE (repository_id, coordinate_hash),
  CONSTRAINT uk_r_package_path UNIQUE (repository_id, asset_path_hash),
  CONSTRAINT uk_r_package_asset UNIQUE (repository_id, asset_id),
  CONSTRAINT chk_r_package_source CHECK (source_kind IN ('HOSTED', 'PROXY'))
);
CREATE INDEX idx_r_package_index_page
  ON r_package_record(
    repository_id, distribution_name, component_name, architecture, package_name, id);
CREATE INDEX idx_r_package_namespace_page
  ON r_package_record(repository_id, distribution_name, package_name, id);
CREATE INDEX idx_r_package_name
  ON r_package_record(
    repository_id, distribution_name, package_name, version_order_key DESC, id DESC);

CREATE TABLE r_package_tombstone (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  coordinate_hash BYTEA NOT NULL,
  distribution_name VARCHAR(384) NOT NULL,
  component_name VARCHAR(128) NOT NULL,
  architecture VARCHAR(64) NOT NULL,
  package_name VARCHAR(128) NOT NULL,
  package_version VARCHAR(255) NOT NULL,
  asset_path VARCHAR(1024) NOT NULL,
  reason VARCHAR(255),
  revision BIGINT NOT NULL,
  deleted_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (repository_id, coordinate_hash)
);
CREATE INDEX idx_r_tombstone_revision ON r_package_tombstone(repository_id, revision);

CREATE TABLE r_suite_state (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(384) NOT NULL,
  desired_revision BIGINT NOT NULL DEFAULT 0,
  desired_at TIMESTAMPTZ(3) NOT NULL,
  pending_since TIMESTAMPTZ(3),
  published_revision BIGINT NOT NULL DEFAULT 0,
  codec_revision INTEGER NOT NULL DEFAULT 0,
  last_published_at TIMESTAMPTZ(3),
  last_error VARCHAR(2048),
  last_error_at TIMESTAMPTZ(3),
  publish_pending BOOLEAN
    GENERATED ALWAYS AS (desired_revision > published_revision) STORED,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, distribution_name)
);
CREATE INDEX idx_r_suite_pending
  ON r_suite_state(repository_id, desired_revision, published_revision);

CREATE TABLE r_snapshot (
  repository_id BIGINT NOT NULL,
  distribution_name VARCHAR(384) NOT NULL,
  revision BIGINT NOT NULL,
  codec_revision INTEGER NOT NULL,
  manifest_json JSONB NOT NULL,
  index_sha256 CHAR(64) NOT NULL,
  group_binding_token BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL,
  published_at TIMESTAMPTZ(3),
  PRIMARY KEY (repository_id, distribution_name, revision),
  CONSTRAINT fk_r_snapshot_suite
    FOREIGN KEY (repository_id, distribution_name)
    REFERENCES r_suite_state(repository_id, distribution_name) ON DELETE CASCADE
);
CREATE INDEX idx_r_snapshot_created
  ON r_snapshot(repository_id, distribution_name, created_at);
CREATE INDEX idx_r_snapshot_retention
  ON r_snapshot(repository_id, distribution_name, revision DESC)
  WHERE published_at IS NOT NULL;

CREATE TABLE r_proxy_distribution (
  repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(384) NOT NULL,
  release_identity VARCHAR(128),
  release_manifest_json JSONB NOT NULL,
  projection_verified BOOLEAN NOT NULL DEFAULT FALSE,
  observed_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (repository_id, distribution_name)
);

CREATE TABLE r_publish_lease (
  lease_key VARCHAR(512) PRIMARY KEY,
  owner VARCHAR(128) NOT NULL,
  fencing_token BIGINT NOT NULL,
  attempt_count BIGINT NOT NULL DEFAULT 1,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  updated_at TIMESTAMPTZ(3) NOT NULL
);
CREATE INDEX idx_r_lease_expiry ON r_publish_lease(expires_at);

CREATE TABLE r_package_relation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repository_id BIGINT NOT NULL,
  package_id BIGINT NOT NULL,
  relation_kind VARCHAR(16) NOT NULL,
  token_value VARCHAR(512) NOT NULL,
  token_hash BYTEA NOT NULL,
  expression_value VARCHAR(1024) NOT NULL,
  CONSTRAINT uk_r_relation UNIQUE (package_id, relation_kind, token_hash),
  CONSTRAINT fk_r_relation_package
    FOREIGN KEY (repository_id, package_id)
    REFERENCES r_package_record(repository_id, id) ON DELETE CASCADE
);
CREATE INDEX idx_r_relation_package
  ON r_package_relation(repository_id, package_id);
CREATE INDEX idx_r_relation_lookup
  ON r_package_relation(repository_id, relation_kind, token_hash, package_id);

CREATE TABLE r_group_snapshot_stage (
  group_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  distribution_name VARCHAR(384) NOT NULL,
  snapshot_revision BIGINT NOT NULL,
  binding_token BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL,
  PRIMARY KEY (
    group_repository_id, distribution_name, snapshot_revision, binding_token)
);
CREATE INDEX idx_r_group_stage_cleanup
  ON r_group_snapshot_stage(
    created_at, group_repository_id, distribution_name, snapshot_revision, binding_token);

CREATE TABLE r_group_binding (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_repository_id BIGINT NOT NULL,
  distribution_name VARCHAR(384) NOT NULL,
  snapshot_revision BIGINT NOT NULL,
  binding_token BIGINT NOT NULL,
  path_value VARCHAR(1024) NOT NULL,
  path_hash BYTEA NOT NULL,
  member_repository_id BIGINT NOT NULL REFERENCES repository(id) ON DELETE CASCADE,
  member_snapshot_revision BIGINT NOT NULL,
  member_path VARCHAR(1024) NOT NULL,
  package_identity VARCHAR(64) NOT NULL,
  sha256 CHAR(64) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  created_at TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT uk_r_group_binding
    UNIQUE (
      group_repository_id, distribution_name, snapshot_revision, binding_token, path_hash),
  CONSTRAINT fk_r_group_binding_stage
    FOREIGN KEY (
      group_repository_id, distribution_name, snapshot_revision, binding_token)
    REFERENCES r_group_snapshot_stage(
      group_repository_id, distribution_name, snapshot_revision, binding_token)
    ON DELETE CASCADE
);
CREATE INDEX idx_r_group_member
  ON r_group_binding(member_repository_id, member_snapshot_revision, id);
CREATE INDEX idx_r_group_page
  ON r_group_binding(
    group_repository_id, distribution_name, snapshot_revision, binding_token, id);

CREATE INDEX idx_r_tombstone_cleanup
  ON r_package_tombstone(deleted_at, repository_id, revision);
CREATE INDEX idx_r_suite_worker
  ON r_suite_state(publish_pending, desired_at, repository_id, distribution_name)
  WHERE publish_pending;
CREATE INDEX idx_r_suite_force_publish
  ON r_suite_state(publish_pending, pending_since, repository_id, distribution_name)
  WHERE publish_pending;
CREATE INDEX idx_r_snapshot_cleanup
  ON r_snapshot(created_at, repository_id, distribution_name, revision)
  WHERE published_at IS NOT NULL;
