{{- if and .Values.securityScanning.enabled .Values.securityScanning.scannerDatabase.persistence.enabled (not .Values.securityScanning.scannerDatabase.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kkrepo.scannerDatabaseClaimName" . }}
  labels:
    {{- include "kkrepo.scannerLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.securityScanning.scannerDatabase.persistence.accessModes | nindent 4 }}
  {{- with .Values.securityScanning.scannerDatabase.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.securityScanning.scannerDatabase.persistence.size }}
{{- end }}
