apiVersion: v1
kind: Service
metadata:
  name: {{ include "kkrepo.fullname" . }}
  labels:
    {{- include "kkrepo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kkrepo.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
