package com.github.klboke.kkrepo.admin.ui;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import org.junit.jupiter.api.Test;

class AdminCleanupPolicyContractTest {
  @Test
  void policyCenteredFlowExposesMultiRepositoryTryRunAndIndependentSchedule() throws IOException {
    String index = resource("/META-INF/resources/admin/index.html");
    String javascript = resource("/META-INF/resources/admin/assets/admin.js");
    String stylesheet = resource("/META-INF/resources/admin/assets/admin.css");

    assertTrue(index.contains("data-view=\"cleanup-policies\""));
    assertTrue(index.contains("id=\"cleanup-policies-view\""));
    assertFalse(index.contains("Choose the target repositories"));
    assertFalse(index.contains("Limits are applied independently"));
    assertFalse(index.contains("cleanup-policy-section cleanup-policy-safety-section"));
    assertFalse(index.contains("<legend>Safety limits</legend>"));
    assertFalse(index.contains("id=\"cleanup-policy-repositories\" multiple"));
    assertTrue(index.contains("id=\"cleanup-policy-repository-trigger\""));
    assertTrue(index.contains("id=\"cleanup-policy-repository-search\""));
    assertTrue(index.contains("id=\"cleanup-policy-repository-options\" role=\"listbox\""));
    assertTrue(index.contains("id=\"cleanup-policy-repository-select-all\""));
    assertTrue(index.contains("id=\"cleanup-policy-repository-clear\""));
    assertTrue(index.contains("Select at least one target repository"));
    assertTrue(index.contains("<legend>Policy details</legend>"));
    assertTrue(index.contains("cleanup-policy-section cleanup-policy-details-section"));
    assertTrue(index.contains("cleanup-policy-section cleanup-policy-rules-section"));
    assertTrue(index.contains("cleanup-policy-section cleanup-policy-schedule-section"));
    assertFalse(index.contains("Leave the run schedule empty for manual execution only."));
    assertFalse(index.contains("cleanup-policy-create-paused-notice"));
    assertFalse(index.contains("Starts paused"));
    assertTrue(index.contains("cleanup-policy-section cleanup-policy-notes-section"));
    assertFalse(index.contains("Operational context"));
    assertTrue(index.contains("id=\"cleanup-policy-notes\" rows=\"2\" maxlength=\"2048\" aria-label=\"Notes\""));
    assertTrue(index.indexOf("<legend>Execution schedule</legend>")
        < index.indexOf("<legend>Notes</legend>"));
    assertFalse(index.contains("<legend>Target repositories</legend>"));
    assertTrue(index.contains("class=\"cleanup-tabs\" role=\"tablist\""));
    assertTrue(index.contains("data-cleanup-tab=\"policies\""));
    assertTrue(index.contains("data-cleanup-tab=\"runs\""));
    assertFalse(index.contains("cleanup-tab-count"));
    assertTrue(index.contains("data-cleanup-panel=\"policies\" role=\"tabpanel\""));
    assertTrue(index.contains("data-cleanup-panel=\"runs\" role=\"tabpanel\""));
    assertFalse(index.contains("cleanup-section-heading"));
    assertTrue(index.contains("class=\"nx-table cleanup-policy-table\""));
    assertTrue(index.contains("id=\"cleanup-policy-page-prev\""));
    assertTrue(index.contains("id=\"cleanup-policy-page-label\">Page 1"));
    assertTrue(index.contains("id=\"cleanup-policy-page-next\""));
    assertTrue(index.contains("id=\"cleanup-policy-page-size\""));
    int cleanupPageSizeStart = index.indexOf("id=\"cleanup-policy-page-size\"");
    int cleanupPageSizeEnd = index.indexOf("</select>", cleanupPageSizeStart);
    String cleanupPageSize = index.substring(cleanupPageSizeStart, cleanupPageSizeEnd);
    assertTrue(cleanupPageSize.contains("<option value=\"10\" selected>10</option>"));
    assertTrue(index.contains("class=\"nx-table cleanup-run-table\""));
    assertTrue(index.contains("id=\"cleanup-run-page-prev\""));
    assertTrue(index.contains("id=\"cleanup-run-page-label\">Page 1"));
    assertTrue(index.contains("id=\"cleanup-run-page-next\""));
    assertTrue(index.contains("id=\"cleanup-run-page-size\""));
    int cleanupRunPageSizeStart = index.indexOf("id=\"cleanup-run-page-size\"");
    int cleanupRunPageSizeEnd = index.indexOf("</select>", cleanupRunPageSizeStart);
    String cleanupRunPageSize = index.substring(cleanupRunPageSizeStart, cleanupRunPageSizeEnd);
    assertTrue(cleanupRunPageSize.contains("<option value=\"10\" selected>10</option>"));
    assertFalse(index.contains("Try Run scan limit / repository"));
    assertFalse(index.contains("Delete limit / repository"));
    assertTrue(index.contains("id=\"cleanup-policy-cron-expression\""));
    assertTrue(index.contains("Run schedule"));
    assertTrue(index.contains("Uses Quartz Cron syntax"));
    assertTrue(index.contains("id=\"cleanup-policy-time-zone\""));
    assertTrue(index.contains("id=\"cleanup-policy-time-zone-options\""));
    assertFalse(index.contains("id=\"cleanup-policy-schedule-enabled\""));
    assertTrue(index.contains("id=\"cleanup-policy-downloaded-help\""));
    assertFalse(index.contains("cleanup-policy-never-downloaded"));
    assertTrue(index.contains("class=\"field-help\""));
    assertTrue(index.contains("id=\"field-help-popover\" role=\"tooltip\" hidden"));
    assertTrue(index.contains("id=\"cleanup-policy-action-menu\" role=\"menu\""));
    assertTrue(index.contains("id=\"cleanup-policy-schedule-preview\""));
    assertTrue(index.contains("id=\"cleanup-policy-schedule-preview-times\""));
    assertTrue(index.contains("class=\"cleanup-policy-section-grid cleanup-policy-rule-grid\""));
    assertTrue(index.contains("id=\"cleanup-run-table\""));
    assertTrue(index.contains("id=\"cleanup-run-detail-modal\""));
    assertTrue(index.contains("id=\"cleanup-run-detail\" hidden"));
    assertTrue(index.contains("class=\"cleanup-run-detail-modal-header\""));
    assertTrue(index.contains("id=\"cleanup-run-detail-content\" aria-live=\"polite\""));
    assertFalse(index.contains("id=\"cleanup-run-result\""));
    assertTrue(index.contains("id=\"cleanup-try-run-form-modal\""));
    assertTrue(index.contains("id=\"cleanup-try-run-form\" hidden novalidate"));
    assertTrue(index.contains("id=\"cleanup-try-run-scan-limit\" type=\"number\" min=\"1\" max=\"10000\""));
    assertTrue(index.contains("No artifacts will be deleted."));

    assertTrue(javascript.contains("/internal/cleanup/policies"));
    assertTrue(javascript.contains("/internal/cleanup/capabilities"));
    assertTrue(javascript.contains("expectedPolicyRevision: view.policy.revision"));
    assertTrue(javascript.contains("scanLimitPerRepository: scanLimit"));
    assertTrue(javascript.contains("mode === \"TRY_RUN\""));
    assertFalse(javascript.contains("window.prompt"));
    assertTrue(javascript.contains("showCleanupTryRunDialog"));
    assertTrue(javascript.contains("submitCleanupTryRun"));
    assertTrue(javascript.contains("setCleanupPolicyScheduleEnabled"));
    assertTrue(javascript.contains("cleanup-policy-more-actions"));
    assertTrue(javascript.contains("openCleanupPolicyActionMenu"));
    assertTrue(javascript.contains("closeCleanupPolicyActionMenu"));
    assertTrue(javascript.contains("handleCleanupPolicyActionMenuKeydown"));
    assertTrue(javascript.contains("data-cleanup-action=\"try-run\""));
    assertTrue(javascript.contains("data-cleanup-action=\"schedule\""));
    assertTrue(javascript.contains("role=\"menuitem\""));
    assertFalse(javascript.contains("cleanup-policy-schedule-toggle"));
    assertFalse(javascript.contains("cleanup-policy-execute\""));
    assertFalse(javascript.contains("cleanup-policy-try-run\""));
    assertTrue(javascript.contains("row-action cleanup-policy-edit"));
    assertTrue(javascript.contains("Enable schedule"));
    assertTrue(javascript.contains("Disable schedule"));
    assertTrue(javascript.contains("return `${schedule.cronExpression} · ${schedule.timeZone}`"));
    assertFalse(javascript.contains("schedule.enabled ? \"enabled\" : \"paused\""));
    assertTrue(javascript.contains("scanLimitPerRepository: current?.scanLimitPerRepository ?? null"));
    assertTrue(javascript.contains("deleteLimitPerRepository: current?.deleteLimitPerRepository ?? null"));
    assertTrue(javascript.contains("cleanupTryRunSubmitting"));
    assertTrue(javascript.contains("cronExpression"));
    assertTrue(javascript.contains("lastDownloadedSupported"));
    assertTrue(javascript.contains("HEAD requests do not count"));
    assertFalse(javascript.contains("includeNeverDownloaded"));
    assertTrue(javascript.contains("setCleanupFieldHelp"));
    assertTrue(javascript.contains("bindFieldHelpTooltips"));
    assertTrue(javascript.contains("scheduleFieldHelpPopoverHide"));
    assertTrue(javascript.contains("/internal/cleanup/schedules/preview"));
    assertTrue(javascript.contains("formatCleanupScheduleTime"));
    assertTrue(javascript.contains("Next two runs"));
    assertTrue(javascript.contains("cleanupRepositorySelection = new Set"));
    assertTrue(javascript.contains("bindCleanupRepositoryPicker"));
    assertTrue(javascript.contains("CLEANUP_TABS = new Set([\"policies\", \"runs\"])"));
    assertTrue(javascript.contains("const CLEANUP_POLICY_DEFAULT_PAGE_SIZE = 10;"));
    assertTrue(javascript.contains("function renderCleanupPolicyPagination()"));
    assertTrue(javascript.contains("results on this page"));
    assertTrue(javascript.contains("cleanupPolicyPage.cursors.push(cleanupPolicyPage.after)"));
    assertTrue(javascript.contains("cleanupPolicyPage.cursors.at(-1) || 0"));
    assertTrue(javascript.contains("function resizeCleanupPolicyPage(size)"));
    assertTrue(javascript.contains("const CLEANUP_RUN_DEFAULT_PAGE_SIZE = 10;"));
    assertTrue(javascript.contains("function renderCleanupRunPagination()"));
    assertTrue(javascript.contains("cleanupRunPage.cursors.push(cleanupRunPage.before)"));
    assertTrue(javascript.contains("cleanupRunPage.cursors.at(-1) || 0"));
    assertTrue(javascript.contains("function resizeCleanupRunPage(size)"));
    assertTrue(javascript.contains("/internal/cleanup/runs?before="));
    assertTrue(javascript.contains("cleanupTabFromHash"));
    assertTrue(javascript.contains("selectCleanupTab"));
    assertTrue(javascript.contains("handleCleanupTabKeydown"));
    assertTrue(javascript.contains("selectCleanupTab(\"runs\")"));
    assertTrue(javascript.contains("refreshCleanupRepositoryOptions([])"));
    assertTrue(javascript.contains("[\"hosted\", \"proxy\"].includes(lowerOrEmpty(repository.type))"));
    assertTrue(javascript.contains("No Hosted or Proxy ${format} repositories are available."));
    assertTrue(javascript.contains("setCleanupRepositoryPickerInvalid(payload.repositoryIds.length === 0)"));
    assertTrue(javascript.contains("Rule or repository changes pause its schedule"));
    assertTrue(javascript.contains("Cleanup policy created. Its schedule is paused."));
    assertFalse(javascript.contains("Run a Try Run before enabling its schedule"));
    assertTrue(javascript.contains("/internal/cleanup/runs/${runId}/cancel"));
    assertTrue(javascript.contains("/internal/cleanup/runs/${runId}/summary"));
    assertTrue(javascript.contains("/internal/cleanup/runs/${runId}/details?itemsPerRepository=50"));
    assertFalse(javascript.contains("/repositories/${repository.id}/items?limit=50"));
    assertTrue(javascript.contains("monitorCleanupRun"));
    assertTrue(javascript.contains("cleanupRunProgressLabel"));
    assertTrue(javascript.contains("run.wouldDeleteSubjects"));
    assertTrue(javascript.contains("would delete"));
    assertTrue(javascript.contains("showCleanupRunDetail"));
    assertTrue(javascript.contains("hideCleanupRunDetail"));
    assertTrue(javascript.contains("document.getElementById(\"cleanup-run-detail\").scrollTop = 0"));
    assertTrue(javascript.contains("Deletion policy <span class=\"cleanup-run-heading-note\">Snapshot used by this run</span>"));
    assertTrue(javascript.contains("Decision details <span class=\"cleanup-run-heading-note\">Showing up to 50 decisions per repository</span>"));
    assertTrue(javascript.contains("class=\"cleanup-run-policy-identity\""));
    assertFalse(javascript.contains("<strong>${escapeHtml(run.state)}</strong><span>Status</span>"));
    assertTrue(javascript.contains("run.criteriaSnapshot"));
    assertTrue(javascript.contains("run.repositorySnapshot"));
    assertTrue(javascript.contains("<dt>Mode</dt>"));
    assertTrue(javascript.contains("<dt>Trigger</dt>"));
    assertFalse(javascript.contains("scrollIntoView({ behavior: \"smooth\", block: \"start\" })"));
    assertTrue(stylesheet.contains(".security-scan-tabs,\n.cleanup-tabs"));
    assertTrue(stylesheet.contains(".cleanup-tab-panel.is-active"));
    assertTrue(stylesheet.contains(
        ".security-scan-pagination,\n.cleanup-policy-pagination,\n.cleanup-run-pagination"));
    assertTrue(stylesheet.contains(".field-help-popover"));
    assertTrue(stylesheet.contains("pointer-events: auto"));
    assertTrue(stylesheet.contains("user-select: text"));
    assertFalse(stylesheet.contains(".field-help[data-tooltip]:not([data-tooltip=\"\"]):hover::after"));
    assertTrue(stylesheet.contains(".cleanup-policy-rule-grid"));
    assertTrue(stylesheet.contains(".form-grid .cleanup-policy-rules-section"));
    assertTrue(stylesheet.contains(".cleanup-policy-rules-section .cleanup-policy-section-copy"));
    assertTrue(stylesheet.contains(".form-grid .cleanup-policy-rule-grid .cleanup-policy-field"));
    assertTrue(stylesheet.contains(".form-grid .cleanup-policy-schedule-grid .cleanup-policy-field"));
    assertTrue(stylesheet.contains("gap: 8px 14px"));
    assertTrue(stylesheet.contains(".cleanup-policy-details-grid > .cleanup-repository-field"));
    assertTrue(stylesheet.contains(".form-grid .cleanup-policy-details-grid .cleanup-policy-field"));
    assertFalse(stylesheet.contains("cleanup-policy-safety-grid"));
    assertFalse(stylesheet.contains("cleanup-policy-automatic-field"));
    assertTrue(stylesheet.contains(".cleanup-try-run-modal-panel"));
    assertTrue(stylesheet.contains(".cleanup-try-run-context"));
    assertTrue(stylesheet.contains(".cleanup-run-detail-modal-panel"));
    assertTrue(stylesheet.contains(".cleanup-run-detail-modal-header .form-modal-close {\n  position: static;"));
    assertTrue(stylesheet.contains("overflow-y: auto;\n  overscroll-behavior: contain;\n  scrollbar-gutter: stable;"));
    assertTrue(stylesheet.contains(".cleanup-run-context-grid"));
    assertTrue(stylesheet.contains(".cleanup-run-rule-grid"));
    assertTrue(stylesheet.contains(".cleanup-run-repository-list"));
    assertTrue(stylesheet.contains(".cleanup-run-detail-section {\n  border: 0;"));
    assertTrue(stylesheet.contains(".cleanup-run-summary > div {\n  padding: 10px 12px;\n  border: 1px solid var(--line);"));
    assertTrue(stylesheet.contains(".cleanup-policy-action-menu"));
    assertTrue(stylesheet.contains(".cleanup-policy-action-menu-item.is-danger"));
    assertFalse(stylesheet.contains("cleanup-policy-never-downloaded-option"));
    assertFalse(stylesheet.contains("cleanup-policy-paused-notice"));
    assertTrue(stylesheet.contains(".cleanup-schedule-preview[data-state=\"valid\"]"));
  }

  private String resource(String path) throws IOException {
    try (InputStream stream = getClass().getResourceAsStream(path)) {
      return new String(Objects.requireNonNull(stream).readAllBytes(), StandardCharsets.UTF_8);
    }
  }
}
