package com.github.klboke.kkrepo.protocol.alpine;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.nio.charset.StandardCharsets;
import java.util.List;
import org.junit.jupiter.api.Test;

class AlpineIndexAndPackageInfoTest {
  private static final String DATAHASH =
      "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

  @Test
  void mapsPkgInfoToCanonicalIndexAndRoundTripsUnknownFields() {
    AlpinePackageInfo info = AlpinePackageInfo.parse("""
        # Generated by abuild
        pkgname = demo
        pkgver = 1.2.3-r4
        pkgdesc = demo package
        url = https://example.invalid/demo
        builddate = 1700000000
        packager = Build <build@example.invalid>
        size = 4096
        arch = x86_64
        origin = demo
        maintainer = Maintainer <maintainer@example.invalid>
        license = MIT
        depend = musl>=1.2
        depend = so:libc.musl-x86_64.so.1
        provides = cmd:demo=1.2.3-r4
        datahash = %s
        """.formatted(DATAHASH));
    String identity = AlpineChecksums.v2Identity("compressed-control".getBytes(StandardCharsets.UTF_8));
    AlpineIndexRecord record = info.indexRecord(identity, 8192);
    AlpineIndexRecord withUnknown = new AlpineIndexRecord(
        new java.util.ArrayList<>() {{
          addAll(record.fields());
          add(new AlpineIndexRecord.Field('x', "retained"));
        }});
    byte[] rendered = AlpineIndex.render(List.of(withUnknown));
    List<AlpineIndexRecord> parsed = AlpineIndex.parse(rendered);
    assertEquals(1, parsed.size());
    assertEquals("demo", parsed.getFirst().packageName());
    assertEquals("musl>=1.2 so:libc.musl-x86_64.so.1", parsed.getFirst().get('D'));
    assertEquals("retained", parsed.getFirst().get('x'));
    assertArrayEquals(rendered, AlpineIndex.render(parsed));
  }

  @Test
  void rejectsMissingDataHashAndMalformedIndex() {
    assertThrows(IllegalArgumentException.class, () -> AlpinePackageInfo.parse("""
        pkgname = demo
        pkgver = 1-r0
        size = 1
        arch = x86_64
        """));
    assertThrows(IllegalArgumentException.class,
        () -> AlpineIndex.parse("P:demo\nV:1-r0\n".getBytes(StandardCharsets.UTF_8)));
  }
}
